docker/Dockerfile, docker/jenkins/build.sh, docker/jenkins/docker-compose.yml, docker/kokkos.patch, examples/distributed_tree_driver/distributed_tree_driver.cpp, test/ArborX_EnableDeviceTypes.hpp.in, test/CMakeLists.txt
- Updating clang to 8.0 will require updating clang-format
- Not tested yet as there is no build system in place
- Unclear what version of OpenMPI to use
Would like to match to Spectrum MPI installed on Summit
=> Docker container

CMakeLists.txt, examples/CMakeLists.txt, test/CMakeLists.txt
Thought about doing something like
```CMake
find_package(Boost QUIET COMPONENTS program_options unit_test_framework)
if(Boost_UNIT_TEST_FRAMEWORK_FOUND)
add_subdirectory(test)
endif()
```
but I am delaying until we introduce a solid logic for enabling/disabling things.
=> Find Boost in subdirectories that actually require it

CMakeLists.txt
In #27 the spelling of `KOKKOS_DEVICES` changed to `Kokkos_DEVICES`.
=> Fix Kokkos_DEVICES spelling

CMakeLists.txt, cmake/FindKokkos.cmake
Part of #36. This is the closest I could come up with. Admittedly, adding `-L${Kokkos_CUDA_LIBRARY_DIR}` is not nice, but should at least work for *nix systems.
=> Move adding CUDA link directory to FindKokkos.cmake

.jenkins, scripts/check_format_cpp.sh
Fix #43 
Instead of printing all source code and report it as files not properly formatted :)
=> Print error message if clang-format executable cannot be found

examples/bvh_driver/bvh_driver.cpp
The test doesn't segfault anymore, also see #45.
=> Add CUDA memory space test in bvh_driver

examples/bvh_driver/bvh_driver.cpp
Fixes #65. We just need a copy for `_argv` and delete its entries instead.
Furthermore, we can use a range-based for loop.
=> Fix memory management in CmdLineArgs

test/tstLinearBVH.cpp
Fixes #75. Since we are now testing the respective `checkResults` function with a positive number of queries, the test would not succeed with the wrong comparison.
=> Add LinearBVH single_leaf_tree test

.jenkins, examples/distributed_tree_driver/distributed_tree_driver.cpp, test/ArborX_BoostRTreeHelpers.hpp
We require C++14 standard but we rely on Kokkos to get the proper compiler flags.
This PR ensures that the `-std=c++14` flag will be present on the compile line in the automated builds on Jenkins.
=> Enable C++14 when building Kokkos in automated CI builds on Jenkins

CMakeLists.txt, examples/distributed_tree_driver/distributed_tree_driver.cpp
Changes:
- Properly align output, 
- Only print information on MPI rank 0, 
- Print relevant run parameters. 
- Replace `overlap` by `shift` such that values different from one and zero have a more intuitive meaning.
=> Improve benchmark for distributed tree

src/ArborX_DistributedSearchTree.hpp, test/ArborX_EnableDeviceTypes.hpp.in, test/Search_UnitTestHelpers.hpp, test/tstLinearBVH.cpp
The motivation for these changes is to be able to instantiate these same unit tests for the "brute force tree" as well.  This PR provides the necessary changes to the helper functions to check results and construct trees.
You may notice I did not bother pushing the changes to all unit tests.  I am still unsure on whether/how to split the file.  Some of the tests (https://github.com/arborx/ArborX/blob/5935ea40b51dd66488f82027d72c1e2a55bf3ae8/test/tstLinearBVH.cpp#L333-L368 in particular) are specifically written for `BVH` and would not make sense for the brute force tree.  Also in my current working version I commented out https://github.com/arborx/ArborX/blob/5935ea40b51dd66488f82027d72c1e2a55bf3ae8/test/tstLinearBVH.cpp#L756-L763.  Anyway my point here is I plan on cleaning these things …
=> Template unit tests on search tree type

examples/bvh_driver/bvh_driver.cpp
`clang` complains:
```
examples/bvh_driver/bvh_driver.cpp:268:21: warning: braces around scalar initializer [-Wbraced-scalar-init]
, _owner_ptrs{{new char[std::strlen(exe) + 1]}}
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
=> Avoid clang warning

examples/bvh_driver/bvh_driver.cpp
Running `clang-tidy` really didn't yield much, but this still looks nicer.
=> Fix a few clang-tidy complaints

test/tstMiscellaneous.cpp
It seems like `gcc` prior to version 6.1.0 requires explicit constructiors here, see https://godbolt.org/z/JqEKVT.
=> Fix test for gcc-5.3.0

docker/Dockerfile
This is a cleaner version where all one would have to change is `CMAKE_VERSION`
=> Verify signature of the checksum when installing cmake

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp
We were accidentally still making assumptions about the primitives.  This PR makes sure that we always go through the access traits to get information about the argument passed to the bvh constructor.  Admittedly we might want to get the execution space some other way in the future but this falls outside the scope of this PR.
=> Fixup for primitives access traits

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp
Will restore later today or tomorrow.
This simplifies greatly history when cherry-picking changes.
=> Temporarily remove concept checks in tree construction

src/ArborX_DistributedSearchTree.hpp, src/ArborX_LinearBVH.hpp
I started working on the documentation of `ArborX::BVH` and realized this was trivial to guarantee.
I cannot think of any reasonable changes in the code that would break that.  (Yes I thought of lazy-construction of the tree and no I do not consider as something worth doing.)
=> Mark BVH::{size,empty,bounds} as noexcept

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_Traits.hpp
* Added 2nd template argument to indicate that access traits are for the BVH constructor
* Geometry tag is deduced from the return type of `Traits::Access::<Primitives,PrimitivesTag>::get()`
=> Refactor access traits

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsAlgorithms.hpp, src/details/ArborX_DetailsConcepts.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_Traits.hpp, test/CMakeLists.txt, test/tstDetailsConcepts.cpp
As promised here https://github.com/arborx/ArborX/pull/111#issue-321706817
restoring the concept checks.
=> Improve error messages in BVH constructor and BVH::query()

cmake/FindKokkos.cmake
This reverts commit 1564b746b428153028f42178e7a9b74bd41000a2.
The compiler identification breaks downstream gfortran builds. The pull
request #49 does not have any information why this modification was
suggested in the first place.
=> Revert "Only add the link path for clang"

src/details/ArborX_DetailsDistributor.hpp
We have no reason to do multiple rounds of MPI communication here, all
of them can be done in a single Alltoall.
=> Simplify createFromSends

src/details/ArborX_DetailsDistributor.hpp
We typically have large message sizes for communication within the same rank. Hence, this also fixes problems with message sizes `MPI` can't handler within one MPI communication call. Also, see #131.
=> Optimize communication within the same rank

src/ArborX_DistributedSearchTree.hpp
This call should normally not involve any communication.
=> Use MPI_Comm_dup to separate ArborX comm context from user's

CMakeLists.txt
Seems we forgot to actually define the `CMake` option.
=> Add CMake option for enabling benchmarks

benchmarks/bvh_driver/bvh_driver.cpp, benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, examples/viz/tree_visualization.cpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsUtils.hpp, test/tstDetailsTreeConstruction.cpp, test/tstDistributedSearchTree.cpp, test/tstLinearBVH.cpp
No reason to fence all execution spaces, only the one we are running.
Meaning, don't do Cuda fence when running in serial.
Related to #45.
=> Replace Kokkos::fence() by ExecutionSpace::fence()

benchmarks/bvh_driver/bvh_driver.cpp, benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, examples/viz/tree_visualization.cpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsUtils.hpp, test/tstDetailsTreeConstruction.cpp, test/tstDistributedSearchTree.cpp, test/tstLinearBVH.cpp
`ExecutionSpace::fence()` is non-static anymore, see https://github.com/kokkos/kokkos/issues/2140.
=> Use ExecutionSpace::fence() as (non-static) member function

src/details/ArborX_DetailsUtils.hpp
Without this patch, we try to assign between a `Kokkos::View` with memory space `CudaSpace` and `CudaUVMSpace` in case `Kokkos` is built with `UVM` support and the original memory space is `CudaSpace`. 
Up to now, we tried to use the default memory space associated with the execution space in `ExclusiveScanFunctor` which turned out to be `CudaUVMSpace` in this case. Hence, the constructor call assigns a `Kokkos::View` with memory space `CudaSpace` to a `KokkosView` with memory space `CudaUVMSpace` which is not allowed.
=> Fix memory space for exclusivePrefixSum

src/details/ArborX_DetailsDistributor.hpp
It seems that there is no reason to first fill a `std::vector` and copying it at the end compared to just using `imports` all the time.
=> Avoiding replicating a View

src/details/ArborX_DetailsSortUtils.hpp
Draft as I need to run scaling studies from the paper on Summit to compare with original version.
Related to #145.
Note that for now, we don't do the check for Thrust, and assume that if Cuda is available, Thrust is. If we encounter situation in the future when that is not the case, we'll introduce that option.
=> Use Thrust for GPU sort

src/details/ArborX_DetailsSortUtils.hpp
This avoids an annoying "dynamic initialization in unreachable code" warning in `sortObjects`.
=> Avoid nvcc warning in sortObjects

src/details/ArborX_DetailsSortUtils.hpp
This fixes all compiler warnings with `-Wall -Wpedantic -Wextra` using `nvcc_wrapper` for me.
=> Avoid more compiler warnings for nvcc_wrapper

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsSortUtils.hpp
On top of #172, this gives using
- 60 MPI processes, 
- 10^7 points/MPI process,
- 10^6 queries/MPI process,
- and a varying number of neighbors for the knn search,
- and CUDA
and the `distributed_tree_driver` benchmark.
|  neighbors | old   |  new   |
|------------|-------|--------|
|  20         | 8.51e0 | 7.23e0 |
| 40          | 2.06e1 | 1.16e1 |
| 80          | 7.38e1 | 2.10e1 |
| 100        | 1.08e2 | 2.54e1 |
| 120        | 1.51e2 | 2.98e1 |
| 140        | 1.97e2 | 3.43e1 |
`Kokkos::BinSort::create_permute_vector` was just ridiculously slow here.
`sortObjects` currently requires us to copy `keys` and we could possibly reuse `scratch` but currently this doesn't show up in the profiling at all.
=> Use sortObjects in sortResults.

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp
A lot of these are stylistic (allocate without initializing + deep copy instead of just initializing) so I am happy to disregard it if someone feels strongly about it. For me, this looks cleaner.
=> Avoid deep_copy or initializing

.jenkins
Right now, the results on any CI build are unpredictable. It may produce
no errors, or it may fail with hundreds of unrelated ones coming from
the system libraries.
I have not had time to investigate it. However, it holds up the process
of merging other PRs. Thus, I'm disabling it for now. It will still
report the warnings, just not fail on them.
=> Disable errors on warnings until figure it out

CMakeLists.txt
Almost every time I configure `ArborX` from a clean directory, I realize a short time later that the default build type neither gives debug flags nor optimization flags and is thus pretty useless.
In `xSDK` mode, the default is `Debug` so I choose that one here. I would also be happy to not allow an empty build type, though.
=> Set default build type to RelWithDebInfo

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp
The changes here should only affect a CUDA-aware MPI implementation.
- If the `DeviceType`'s memory space is `Kokkos::Host` we, of course, do everything in host memory space. 
- If the `DeviceType`'s memory space is `Kokkos::Cuda` and we enable `KOKKOS_USE_CUDA_AWARE_MPI`, the permutation array now is stored on the device and `Distributor::doPostsAndWaits` doesn't allow memory on the device anymore, but just uses the permutation array directly since the input array is stored on the device. 
- If the `DeviceType`'s memory space is `Kokkos::Cuda` and `KOKKOS_USE_CUDA_AWARE_MPI` is disabled, the input array for `Distributor::doPostsAndWaits` is stored on the host so we should also create the permutation array on the host.
=> Keep permutation on the device

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, src/ArborX_DistributedSearchTree.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Using access traits in the benchmark to demonstrate that it works.
=> Enable predicates access traits in distributed search tree

src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp
When calling `createFromSends` in `DistributedSearchTreeImpl::communicateResultsBack` the input is already batched, but we currently don't try to benefit from that. Given that even for examples that only require very few communication most of the time related to MPI communication is spent in `createFromSends` (and for communication heavy applications even more so), it might be worth exploiting this.
The new overload for `sortAndDetermienBufferLayout` essentials just computes the correct permutation for the batched ranks and reconstructs the total permutation from that.
~~I still need to run benchmarks.~~
=> Exploit batched input in createFromSends

benchmarks/bvh_driver/bvh_driver.cpp, test/tstDetailsAlgorithms.cpp, test/tstDetailsTreeConstruction.cpp, test/tstDetailsTreeTraversal.cpp, test/tstHeapOperations.cpp, test/tstLinearBVH.cpp
The command used:
```
find . -name '*hpp' -or -name '*cpp' -exec aspell --mode ccpp --check {} \;
```
=> Spellchecking comments

README.md, docs/traits.md
* I realized I forgot the `static` keyword in the access traits documentation.
* Also I fixed the link to the API documentation in the README
=> Minor fix for the API documentation

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
notify() was never called, so the node type was never stored. This bug
did not allow changing the node type from the command line.
=> Fix node parsing in the distributed benchmark

benchmarks/bvh_driver/bvh_driver.cpp
The PR contains the patches to produce valid JSON output.
The functionality of the driver was slightly changed. It no longer produces any neighbor statistics output, and version and hash were made optional by introducing a `--no-header` command line option.
I consider this to be the simplest way to address the problem. Other approaches are more involved. Ideally, the version/hash output would depend on the `--benchmark_format=json` option, but that would require more intimate interaction between boost program options and benchmark options parsing.
=> Allow valid JSON output from benchmark

docker/Dockerfile
Warnings seem to be coming from building the Docker image.
~~Try piping stderr to /dev/null so the warnings are not printed to the screen.~~
Piping stderr did not work.  Pass `-w` flag (suppress all warnings, including those which GNU CPP issues by default) when building Boost instead.
This is ready for review/merge.
=> Attempt to filter out unrelated warnings in the builds

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsNode.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, test/tstDetailsTreeConstruction.cpp
Motivation:  this will let us copy trees between host and device and enable checkpoint/restart if that's something we want to get into.
Note that indices are store as `ptrdiff_t` that has the same size as a pointer so that we do not change the alignment.
=> Store indices of children nodes rather than pointer in the bounding volume hierarchy

src/ArborX_LinearBVH.hpp
When profiling things, sometimes one has to do arithmetic to figure out
whether it is the Morton codes sorting that slows down, or leaf
initialization. Might as well separate them.
=> Separate leaves initialization profiling region into two regions

benchmarks/bvh_driver/bvh_driver.cpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, test/tstLinearBVH.cpp
Fix #206.
I added a new boolean parameter. I opted to have it before `buffer_size` as it is common from both kNN and spatial searches, while the  parameters after it are specific (`buffer_size` to spatial, `which` to kNN). This choice made the patch slightly larger than it could have been.
I also decided to keep the default to sorted as of now. I'm not married to it, but this allows us to still be able to compare benchmark results with older runs.
=> Optional sorting of predicates

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, test/tstDetailsTreeConstruction.cpp
~~Not entirely done with dropping the `DeviceType` template parameter from the `Details::TreeConstruction` struct and turning it in a namespace.
There are some subtleties with views that I still need to work out.~~
Done
=> Take execution space as argument in tree construction

src/ArborX_DistributedSearchTree.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsUtils.hpp, test/ArborX_BoostRTreeHelpers.hpp, test/tstDetailsTreeConstruction.cpp, test/tstDetailsUtils.cpp, test/tstLinearBVH.cpp
Deprecated older form to emit warnings rather than break code downstream
=> Update STL-like algorithms to take execution space as first argument

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Following up on https://github.com/arborx/ArborX/pull/248#issuecomment-605071389
=> Drop extra parallel_reduce() when sorting objects in distributed tree

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp
Constructor and query() take execution space as first argument.
Old syntax is still valid for now.
=> Template BVH on memory space

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
This is the modification of the `distributed_tree_driver` benchmark used in https://github.com/arborx/ArborX/pull/199#issuecomment-562231451.
=> Allow queries in benchmark to differ from local points

src/details/ArborX_DetailsKokkosExt.hpp, test/ArborX_BoostRangeAdapters.hpp, test/tstDetailsDistributedSearchTreeImpl.cpp, test/tstDetailsTreeConstruction.cpp
`SpaceAccesibilty` has been promoted to the `Kokkos ::` namespace a while ago and we require version 3.0
It is only in `Impl::` for backward compatibility, we do not need to wait for Kokkos to deprecate it to act.
=> Cleanup Kokkos::{Impl:: -> }::SpaceAccesibility<Space, MemorySpace>

src/ArborX_DistributedSearchTree.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsKokkosExt.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, src/details/ArborX_DetailsUtils.hpp, src/details/ArborX_Traits.hpp, test/ArborX_BoostRangeAdapters.hpp, test/Search_UnitTestHelpers.hpp
The only headers other than `<Kokkos_Core.hpp>` that may be included specifically are `Kokkos_Macros.hpp` or things like `Kokkos_Pair.hpp` or `Kokkos_Array.hpp`
=> Stop pretending we can cherry-pick Kokkos headers

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
https://github.com/arborx/ArborX/pull/256#discussion_r403223037
Fixup for #257
=> Get rid of one stray view initialization in forwardQueries()

src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsUtils.hpp, test/tstDetailsDistributedSearchTreeImpl.cpp
In particular, this should deal with `Distributor`.
The cases that don't work yet are marked (most likely due to the bug reported by @dalg24 in `Kokkos`).
=> Use execution_space in Kokkos::parallel_ and Kokkos::deep_copy

docker/Dockerfile
Given that this periodically times out, and cmake never does, maybe it is a better idea to use the default keyservers for LLVM key too.
=> Do not specify keyserver for LLVM key

docker/Dockerfile, docker/Dockerfile.pgi
Verify PGP signature (because our failure rate for not being able to download key is not high enough) and do not require to find out the SHA256 of a release.
=> Update Boost installation process in Docker images

CMakeLists.txt
Before, if one ran make from a subdirectory, the record_hash command was
not run, and thus hash was not updated. Thus, if you stayed in the same
subdirectory, but switched branches/hashes, the executable kept having
the same hash (unless checkout also touched CMakeLists.txt).
This commit fixes it by making ArborX target depend on
always-out-of-date record_hash target.
Fix #264.
=> Properly update hash in version file when building from subdirs

src/details/ArborX_DetailsSortUtils.hpp
Fix #263 
Change `Kokkos::View<..., DeviceType> -> Kokkos::View<..., MemorySpace>` to `morton_indices` in the BVH constructor caused the wrong `sortObjects()` overload to be called.  This bug was introduced in #251
=> Fixup Details::sortObject() overload for Cuda execution space

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile.pgi, docs/build.md, src/ArborX_DistributedSearchTree.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_Box.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsContainers.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsNode.hpp, src/details/ArborX_DetailsPriorityQueue.hpp, src/details/ArborX_DetailsStack.hpp, src/details/ArborX_Point.hpp, src/details/ArborX_Predicates.hpp, src/details/ArborX_Sphere.hpp
The main motivation for updating to 3.1 it to allow HIP backend. We could have done magic to still work with 3.0, but we decided not to bear cost of supporting that.
=> Kokkos 3.1

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsTreeConstruction.hpp
While looking at the causes of CUDA construction slowdown in #235 I noticed that we are using `size_t` for permutations. That PR will change everything to `int` anyways, so I was curious to see whether changing permutation indices to `unsigned int` changed anything.
Apparently, it does. The results on Summit are below. A brief summary: makes no difference for CPU (on my workstation it sped up by 10%), but makes significant difference for GPU, especially for small size constructions (which is exactly the problem in #235).
```
$ compare_bench.py benchmarks master.json unsigned_permute.json | grep median                                                            
BM_construction<ArborX::BVH<Serial>>/10000/0/manual_time_median                                  +0.0085         +0.0085 …
```
=> Use unsigned int for permutation indices instead of size_t

docs/bounding_volume_hierarchy.md, docs/traits.md
Per https://github.com/arborx/ArborX/pull/279/files#r414063125
=> Use scope guards in the documentation and examples

.jenkins, CMakeLists.txt
Assumption: most users only care about installing and using ArborX.
=> Disable tests, examples, benchmarks by default

test/CMakeLists.txt
Related to #168
Note that benchmarks work with any Boost (at least, Boost >= 1.67.0). Tested with 1.70.0.
=> Require boost < 1.69 for CUDA-enabled tests

benchmarks/bvh_driver/bvh_driver.cpp
The code was erroneously subtracting a constant from the radius. That
was a historic artifact coming from the original DTK code (commit
[8610a49d](https://github.com/ORNL-CEES/DataTransferKit/commit/8610a49dd3ae2839a0b267f3f41584c7c859eabe) when we were constructing boxes and not points. This code was
trying to adjust for the box size 1.
As we now construct points, this is not necessary.
=> Fix radius calculation for on-node benchmark

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsSortUtils.hpp
Running more profiling, it turned out that we benefit from `CUDA`-aware MPI when we have a lot of data (which was the case for the test case I used so far). Otherwise, non-`CUDA`-MPI seems to be better since the fewer copies in our code are not worth the longer runtime for the MPI calls.
While doing this, I discovered that a major difference in `doPostsAndWaits` is due to the permutation being executed on the device for `CUDA`-aware MPI. This pull request makes sure that we always perform the permutation on the device and only copy the data back to the host afterward.
Radius:
|  # MPI processes | old   |  new   |
|------------|-------|--------|
|   1        | 2.34e0 | 1.80e0 |
|   6        | 2.77e0 | 2.27e0 |
|  12        | 2.78e0 | 2.23e0 |
|  24        | 2.89e0 | 2.32e0 |
|  48        | …
=> Always permute on the device

docker/Dockerfile, docker/Dockerfile.pgi
Building boost did not use `SCRATCH_DIR`, and there was no `cd ..`. So when `rm -rf boost*` was executed, we were still inside `/boost`. This commit changes it to approach used when building all other tpls, and blows away `SCRATCH_DIR` at the end.
=> Properly clear out boost directory when building Docker image

src/details/ArborX_DetailsSortUtils.hpp
I encountered the bug with CUDA-10.0 and LLVM/Clang v10.0.0
Rather than attempting to discriminate combinations of CUDA/Clang versions, I suggest we use the workaround unconditionally for now.
=> Use Clang workaround for Thrust regarless of the version

cmake/ArborXConfig.cmake.in
This PR is simply to facilitate the discussion of the best approach to provide transitive path to Kokkos when using ArborX.
The current approach was taken from [Cabana](https://github.com/ECP-copa/Cabana/blob/27a31ab987d978eff18b443de1f5dc658c02237e/core/src/CabanaConfig.cmakein#L2-L4).
Feel free to close if you think this is useless.
=> Retain the original path to Kokkos

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
We need to pass the actual arguments to Kokkos if we want it to consume some of the options such as `--kokkos-threads`.
=> Pass the actual command line arguments to Kokkos

.jenkins, docker/Dockerfile, docker/Dockerfile.pgi, src/details/ArborX_DetailsDistributor.hpp
Following up on https://github.com/arborx/ArborX/issues/295#issuecomment-625326270
Scope creeped quite a bit...
List of changes:
- Upgrade OpenMPI to v4
- Allow non-CUDA enable MPI with CUDA build
- Import gpg keys from local server
- Update clang to v10
- Add `OMP_NUM_THREADS` and `MPI_MAX_NUMPROCS` in testing
- Replace one CUDA 10.1 build by 10.2
- Reorganize backends distribution among builds
=> Update testing framework

src/details/ArborX_DetailsTreeTraversal.hpp, test/tstLinearBVH.cpp
Comparing the current implementation with the original Karras algorithm.
I have spent little time figuring why the new one is so much faster, and whether it could be reimplemented using the existing `Stack` structures (I tried doing a straightforward replacement, but that immediately slowed down).
=> Workaround for Stack performance

CMakeLists.txt
* Per our discussion this is a left over from pre 3.0 Kokkos and was not intentional
* The `QUIET` option makes little sense when combined with `REQUIRED`
* This will print the messages from Kokkos including what backend was enabled
=> Drop QUIET option when finding Kokkos

docker/Dockerfile, docker/Dockerfile.pgi
It also tries to find gtest when tests are enabled, which fails on
CADES, for example.
=> Do not build benchmark tests when building container

.gitlab-ci.yml
We need to use the correct `master` branch now, that the files should all be there.
=> Replace master-ci by master

.github/workflows/gitlab-ci.yml
As discussed with @aprokop, it is useful to prepend the branch name with the repository name when pushing to `GitLab` since the CI is triggered from the forks. This pull request for example corresponds to https://code.ornl.gov/ecpcitest/alexa/-/tree/masterleinad/ArborX/change_github_workflow_base
Do we want to keep the modified workflow (currently in https://github.com/masterleinad/gitlab-mirror-and-ci-action) in https://github.com/arborx instead?
=> Change GitHub workflow base

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp
As I was going over the API, I realized I that `BVH::bounds` was currently not annotated `__host__ __device__` and I could not think of a good reason not to.
I considered returning a const reference to the bounding volume but I don't think this is a good idea because I don't have evidence that this improve performance and it would enable memory access violations.
When looking for places we call that member function, I stumbled over the two overloads of `sortQueriesAlongZOrderCurve` and I think this was a mistake.
=> Let BVH::bounds() be a KOKKOS_FUNCTION

examples/CMakeLists.txt, examples/callback/CMakeLists.txt, examples/callback/example_callback.cpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, test/tstCallbacks.cpp
Example was long due and not requesting to tag callbacks makes the most common case easier and allows for generic lambdas.
=> Add example for callbacks and lift requirement for tagging inline

.gitlab-ci.yml, benchmarks/bvh_driver/bvh_driver.cpp, benchmarks/point_clouds/point_clouds.hpp
The main motivation is to not carry the hardcoded configuration for performance benchmark, allowing faster turnaround for testing. In addition, this would allow the paper branch to only have nanoflann related changes.
It needs some pruning and maybe improving interface. It works, at least. Would appreciate some help in improving the code, as it has several ugly places.
As an example, one would run this as
```shell
./ArborX_BoundingVolumeHierarchy.exe \
--exact-spec '10000/10000/10/0/0/1/3' \
--exact-spec '10000/1000/10/0/0/0/2'  \
....
```
Also, because of not using `BENCHMARK_TEMPLATE`, we are no longer married to just integers, so we could actually replace some `0` and `1` by `filled`, `hollow` and `sort/no_sort` in the right places, or make that string more readable in general.
=> Add batch mode to bvh on-node driver

benchmarks/bvh_driver/bvh_driver.cpp
It turns out that the extra information we output isn't compatible with comparing benchmark results in JSON format. In particular, the benchmark comparison tool fails with the output we currently create.
In my opinion, just deleting these lines is the simplest solution since the output is redundant anyway.
=> Remove verbose output from BVH driver

.github/workflows/gitlab-ci.yml, .gitlab-ci.yml
A couple of improvements:
- Don't run for pull requests (that doesn't work anyway)
- Name the `master` branch executable according to the branch hash to avoid it being deleted when another pipeline is running simultaneously
- Import the benchmark results back to GitHub, see https://github.com/masterleinad/ArborX/runs/743442620?check_suite_focus=true.
This relies on the changes in https://github.com/masterleinad/gitlab-mirror-and-ci-action/tree/get_final_artifacts. I would update `master` if we find this acceptable as is.
=> Improve GitLab CI

src/details/ArborX_DetailsUtils.hpp
Fix for clang-tidy warning:
```
src/details/ArborX_DetailsUtils.hpp:135:1: warning: return type 'typename Kokkos::ViewTraits<const int *, Device<Threads, HostSpace>>::value_type' (aka 'const int') is 'const'-qualified at the top level, which may reduce code readability without improving const correctness [readability-const-return-type]
```
This was an oversight on my part.
=> Fixup: Do not let lastElement() return type be const-qualified

src/details/ArborX_DetailsHeap.hpp, src/details/ArborX_DetailsPriorityQueue.hpp
The identifiers with a double underscore anywhere are reserved.  I knew I would have to change this one day or the other and kept kicking the can down the road.  I was experimenting with clang-tidy and it choked on it.
=> Drop double underscore prefix in bubble{Down,Up}

src/details/ArborX_AccessTraits.hpp
These currently show up in DTK. An alternative to provide another constructor to `Point` that takes `double` arguments.
=> Fix some more narrowing conversion warnings

test/tstContainerAdaptors.cpp, test/tstDetailsTreeConstruction.cpp, test/tstLinearBVH.cpp
Building with a `Kokkos` installation that has compiler warnings enabled, forces, i.a., `-Wshadow`.
This is what I currently need to compile warning-free.
=> Avoid -Wshadow warnings

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Basically #271 but for distributed trees
Cleaning up distributed tree implementation details is more involved than anticipated.
My short term plan is to get all `queryDispatch` overloads out of the struct templated on the device type and 
then to introduce the new overloads that take a view of "pair" local index + rank instead of two separate views.
=> Allow non device type template parameter for output views in query() on distributed trees

src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp
Main motivation is reduce maintenance cost prior to integrating
stackless traversals. The code remains in history, and could be easily
resurrected if desired.
=> Remove deprecated nearest traversals

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsKokkosExt.hpp, src/details/ArborX_DetailsMortonCode.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, test/tstDetailsTreeConstruction.cpp
I'm opening this PR just to document the work, share my thoughts and solicit feedback.
This is an alternative simpler implementation of the Karras algorithm as described in the paper:
Apetrei, C. (2014). Fast and simple agglomerative LBVH construction.
It gets rid of some heavy machinery, and constructs the hierarchy in a single bottom-up pass, keeping track of the ranges for each internal node.
~The current implementation work and produces correct result. It also, as expected, speeds up the construction. However, it also affects traversal, sometimes negatively (+15% on large problems for Cuda when queries are unsorted).~
~My current understanding is that the hierarchy is identical, but the internal node numbering is a permutation of Karras. In the original Karras, the children node have …
=> Apetrei's construction algorithm

.jenkins, test/Search_UnitTestHelpers.hpp
I don't understand how this slipped through. We have CI testing with `ARBORX_ENABLE_MPI=OFF`. But it did not catch it? This was immediately caught on my workstation.
=> Add MPI guards for test helpers

src/ArborX_LinearBVH.hpp
Fix #376.
The issue was reported by @uhetmaniuk
We call `Kokkos::Profiling::pushRegion()` at the very top of the constructor and when zero primitives are passed we are exiting early and forget to call `Kokkos::Profiling::popRegion()`.
Having a local empty tree is not uncommon with the distributed tree and this was causing the Space Time Stack tool to crash with `Program ended before "ArborX:BVH:construction" ended`.
=> Fix profiling region in BVH constructor

test/CMakeLists.txt, test/VectorOfTuples.hpp, test/tstKokkosToolsAnnotations.cpp
Related #362 except that it focus on enforcement and does not apply any change yet.
This is going to fail because it requires Kokkos 3.2
Should I insert an `#if KOKKOS_VERSION >= 30200` or conditionally add from CMake?
=> Ensure that all kernels from BVH are properly marked

src/ArborX_DistributedSearchTree.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Proposed resolution for #368
Stores the duplicated comm in a smart pointer with a custom deleter.
=> Avoid double free in distributed tree

.clang-tidy, examples/halo_finder/ArborX_HaloFinder.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsNode.hpp, src/details/ArborX_DetailsPriorityQueue.hpp, src/details/ArborX_DetailsUtils.hpp, test/ArborX_BoostGeometryAdapters.hpp, test/ArborX_BoostRangeAdapters.hpp
We forgot to set the header filter so no header files were checked. This pull requests fixes all `clang-tidy 9` complains.
=> Apply clang-tidy also to header files

src/details/ArborX_DetailsTreeVisualization.hpp, test/ArborX_BoostRTreeHelpers.hpp
This is consistent with what we did in TreeConstruction, TreeTraversal, and other implementation details.
I ran into this issue when prototyping templating the bounding volume type in the BVH.  I had the choice between updating the forward declaration or removing it, I chose the latter.
=> Remove BVH forward declaration in viz

.jenkins
Test machines may host concurrent CI builds.  This makes sure the ArborX build use the appropriate GPU.
=> GPU isolation on CI builds

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBufferOptimization.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, test/Search_UnitTestHelpers.hpp, test/tstKokkosToolsAnnotations.cpp
Will need to be rebased onto #380 
Using
* `ArborX::BVH::BVH::` for all views allocated from the constructor
* `ArborX::BVH::queries::` for all views allocated during the search
* `ArborX::Sorting::` for the view with the permutation indices from the sorting utility function
* `Testing::` for all view allocated from the unit tests
Partially addressing #362
=> Prefix view names allocated from BVH

src/details/ArborX_DetailsSortUtils.hpp
This one sneaked in as a combination of a) @dalg24 not testing with Cuda, and b) Kokkos 3.2 not used in CI (and thus labels are not checked).
=> Fix one missed label

src/ArborX_DistributedSearchTree.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, test/CMakeLists.txt, test/tstDistributedKokkosToolsAnnotations.cpp, test/tstKokkosToolsDistributedAnnotations.cpp
Fixes #377. The output for `ArborX_DistributedTree.exe` using `space-time-stack` is
```
[...]
TOP-DOWN TIME TREE:
<average time> <percent of total time> <percent time in Kokkos> <percent MPI imbalance> <remainder> <kernels per second> <number of calls> <name> [type]
=================== 
|-> 3.65e-02 sec 57.1% 102.6% 0.0% 0.0% 7.13e+03 1 ArborX::DistributedSearchTree::nearest_query [region]
|   |-> 2.22e-02 sec 34.8% 101.9% 0.0% 0.6% 5.94e+03 1 ArborX::DistributedSearchTree::deviseStrategy [region]
|   |   |-> 1.73e-02 sec 27.1% 97.9% 0.0% 0.1% 2.84e+03 2 ArborX:BVH:nearest_queries [region]
|   |   |   |-> 1.58e-02 sec 24.7% 98.5% 0.0% 0.1% 1.27e+03 2 ArborX:BVH:two_pass [region]
|   |   |   |   |-> 1.53e-02 sec 24.0% 99.1% 0.0% 0.9% 6.54e+02 2 ArborX:BVH:two_pass:first_pass [region]
|   | …
```
=> Profiling regions for DistributedSearchTree

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, src/ArborX_DistributedSearchTree.hpp, src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, test/tstDetailsBatchedQueries.cpp, test/tstDetailsBufferOptimization.cpp, test/tstDistributedSearchTree.cpp, test/tstKokkosToolsDistributedAnnotations.cpp
Analogon to #381 for DistributedSearchTree. I still like to distinguish between nearest_queries and spatial_queries if we can but won't fight over it. Also, we could append `ArborX::` to `Testing` in both pull requests.
Output for `ArborX_DistributedTree.exe`:
```
ALLOCATIONS AT TIME OF HIGH WATER MARK:
23.2% internal_and_leaf_nodes
14.4% ArborX:BVH:spatial_queries/ArborX:BVH:two_pass/ArborX:BVH:two_pass:second_pass/Testing::values
14.4% Testing::values
8.7% Testing::bounding_boxes
7.2% ArborX::DistributedSearchTree::forwardQueries::import_ranks
7.2% ArborX::DistributedSearchTree::forwardQueries::import_ids
7.2% ArborX::DistributedSearchTree::forwardQueries::import_ranks
7.2% ArborX::DistributedSearchTree::forwardQueries::import_ids
4.3% Testing::values
2.3% …
```
=> Profiling distributed search tree views

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp, test/tstKokkosToolsDistributedAnnotations.cpp
While preparing this pull request, I realized that we are both using `DistributedTree` and `DistributedSearchTree`. We should probably just choose one of them and would slightly lean towards `DistributedSearchTree` (or an abbreviation like DST) since this is the actual name of the class.
Maybe, in another pull request.
=> Add check for labels in kernels for DistributedSearchTree

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, test/tstDetailsTreeConstruction.cpp
As suggested in #393 deferring leaf node initialization to the main generate hierarchy kernel.
Besides one less kernel launch, this pushes all code that knows about the underlying node type into the same functor.
=> Initialize leaf nodes in hierarchy generation

.jenkins
This pull request tries to just ignore the #pragma-message warning generated for `ArborX_DistributedSearchTree.hpp` in the Jenkins plugin.
=> Ignore #pragma-messages warnings in CI

benchmarks/bvh_driver/bvh_driver.cpp
Only the check for valid backends was incomplete.
=> Allow using HIP in BVH benchmark

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, src/details/ArborX_Predicates.hpp, test/tstDetailsTreeConstruction.cpp
This is the uncontroversial part of #386 that is needed by #364 
Essentially deducing the node type from the bvh or making it a template parameter depending on the context.
I renamed `BVH::{Node -> node_type}` for consistency with the `BVH::bounding_volume_type` member type and to avoid ambiguities with the actual type.
=> Reduce number of places that need to see the node type definition

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsNode.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, test/tstDetailsTreeConstruction.cpp
Here's a figure to help understanding what ropes are (c/o [1]):
[1] Wang, X., Tang, M., Manocha, D., & Tong, R. (2018). Efficient BVH‐based Collision Detection Scheme with Ordering and Restructuring. In Computer Graphics Forum (Vol. 37, No. 2, pp. 227-237).
=> Implement stackless tree traversal using escape index (ropes)

test/tstLinearBVH.cpp
Using Boost.Test native expected failures specification when the HIP backend is enabled.
Other options were to handle the failure on the CMake or even Jenkins side.  I am proposing this solution because it is most concise and fine-grained.
=> Temporary workaround for failures in HIP CI build

src/ArborX_LinearBVH.hpp
Motivation: This is one point of departure between the HIP and the Cuda backend (besides sorting using Thrust) and it would be nice if we can get rid of it before running more extensive performance analysis between the two backends.
=> Use ropes on AMD GPUs as well

.gitlab-ci.yml, benchmarks/bvh_driver/bvh_driver.cpp, test/ArborX_BoostRTreeHelpers.hpp
The callbacks simply count the number of found neighbors.
The PR should be pretty straightforward. One thing that we need to decide on is whether we want to test both types of queries on the same number of points for performance testing. Testing both on everything essentially doubles testing time.
If decide to not test the same way, the answer will depend on what we think is more important.
I think my current position would be to test all numbers for pure callbacks, and not more than 3 for the old callbacks (with indices and offsets).
=> Add testing of new query overload to the perf benchmark

test/tstKokkosToolsAnnotations.cpp
While looking into SYCL support, I realized that we use `Kokkos::Sort` functionalities in all backends except for `CUDA`.
=> Fix annotations for non-CUDA invocations

benchmarks/bvh_driver/bvh_driver.cpp, examples/callback/example_callback.cpp, examples/dbscan/ArborX_DetailsDBSCANVerification.hpp, test/CMakeLists.txt
These are changes that are needed to check whether ArborX can build with the Kokkos experimental backends OpenMPTarget and SYCL.  I have had to make these changes manually several times and I am sure other have too.  I think it is time to merge it in.
I do not believe that having this in will confuse users and expect that we will get it working soon enough.
=> Enable all experimental backends

benchmarks/bvh_driver/bvh_driver.cpp, benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, src/ArborX_DistributedTree.hpp, src/ArborX_LinearBVH.hpp, test/ArborX_BoostRTreeHelpers.hpp, test/Search_UnitTestHelpers.hpp, test/tstDistributedTree.cpp, test/tstKokkosToolsAnnotations.cpp, test/tstKokkosToolsDistributedAnnotations.cpp, test/tstLinearBVH.cpp
The only thing that's left is to somehow deprecate both. My first attempt of deprecation was unsuccessful. But removing them works.
=> Stop using BVH<DeviceType> and DistributedTree<DeviceType> internally

src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsBufferOptimization.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, test/tstCallbacks.cpp, test/tstLinearBVH.cpp
=> Enable early termination of the tree traversal for spatial predicates

examples/dbscan/ArborX_DBSCAN.hpp
I'm still not sure if this is the best way to do, but it speeds up postproccessing on V100 for halo finding from 0.050 to 0.027. 3% overall time improvement for the win :) The improvements are better on AMD.
A side note: `--verify` option does not test this. The only way right now to validate this patch is to run with `--output-sizes-and-centers` and compare the output to master.
=> Speed up DBSCAN post-processing

src/details/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp
This is pr to make make ArborX::Ray working as a predicate for batched queries.
I ran into and then resolved an issue #435.
Fix #435
=> Fix ambiguities arising from using initializer lists without specifying a type

.clang-tidy, benchmarks/bvh_driver/bvh_driver.cpp, examples/callback/example_callback.cpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp, src/details/ArborX_DetailsBufferOptimization.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, test/Search_UnitTestHelpers.hpp, test/tstCallbacks.cpp, test/tstDetailsBufferOptimization.cpp, test/tstDistributedTree.cpp, test/tstLinearBVH.cpp
=> Change signature of the nearest callback

src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
See regression [here](https://github.com/arborx/ArborX/pull/366#issuecomment-749245689).
Comparing with 6224c97:
```
BM_construction<ArborX::BVH<Cuda>>/10000/0/manual_time_median                                       +0.0036         +0.0029          1405          1410          1420          1424
BM_construction<ArborX::BVH<Cuda>>/100000/0/manual_time_median                                      +0.0021         +0.0024          2149          2154          2540          2546
BM_construction<ArborX::BVH<Cuda>>/1000000/0/manual_time_median                                     +0.0215         +0.0015          6896          7044          7385          7397
BM_construction<ArborX::BVH<Cuda>>/10000/1/manual_time_median                                       +0.0030         +0.0027          1404 …
```
=> Fix performance regression introduced in #366

src/details/ArborX_Box.hpp, src/details/ArborX_DetailsAlgorithms.hpp, src/details/ArborX_DetailsTreeConstruction.hpp
Prefer built-in reducer with user-defined scalar type to custom reducer because it is not currently supported with the Kokkos OpenMPTarget backend.
I was able to pass all examples, benchmarks, and tests with these changes (modulo minor change to tools annotation check because one allocation was not prefixed properly in Kokkos).  I did not enable MPI.
This is only a draft because I wanted to clarify requirements on the scalar type to work with build-in reducers.
=> Use Kokkos built-in reducer in bounding scene calculation

src/details/ArborX_Box.hpp
Amend to #439 because new SYCL build introduced in #423 did not run.
SYCL backend reduction displays similar type requirements than the OpenMPTarget.
The code should still been see as a workaround.  We reported the issue and will address on the Kokkos side.
=> Fixup builtin reducer type requirements for SYCL backend 

benchmarks/bvh_driver/bvh_driver.cpp, examples/dbscan/ArborX_DBSCAN.hpp
It may happen that the last kernel in ArborX is a Kokkos::parallel_for.
As ArborX does have a guaranteed fence() at the end, what could happen
is that that kernel is launched, and ArborX returns. Thus, when the
ending timer is called, the kernel has not been completed yet. Thus, the
measured time would be wrong in this case.
=> Fence ArborX calls in the benchmark and (optionally) DBSCAN

benchmarks/bvh_driver/bvh_driver.cpp
It is useful on its own. It is also a good way to resolve #410 blocking issue, as Google Benchmark itself will compute the statistics on the rate.
The output looks like this:
```
./ArborX_BoundingVolumeHierarchy.exe --benchmark_filter=construction.*Serial --benchmark_repetitions=2
rk_out_format=json                                                                                                                                 
ArborX version: 0.9 (dev)                                                                                                                          
ArborX hash   : bc6ac790                                                                                                                         
2021-01-09 13:21:38                           
Running …
```
=> Print out rates in the benchmark

examples/dbscan/ArborX_DBSCAN.hpp, examples/dbscan/ArborX_DetailsDBSCANVerification.hpp, examples/dbscan/dbscan.cpp, src/details/ArborX_DetailsHeap.hpp, test/tstHeapOperations.cpp
We know that Kokkos::BinSort struggles on arrays with duplicated
indices, which is certainly the case here, as the sort is called on
cluster indices.
The new approach completely avoids that. And, in fact, seems to be
faster.
=> Update DBSCAN post-processing to avoid calling sort

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, examples/access_traits/example_cuda_access_traits.cpp, examples/access_traits/example_host_access_traits.cpp, examples/callback/example_callback.cpp, test/tstAccessTraits.cpp, test/tstCallbacks.cpp
cc @wjge 
NOTE order between `static` and the function annotation does not actually matter.  I picked the one I liked better (today at least)
NOTE qualification `ArborX::` is not strictly necessary in the body of the access traits.  I added it for clarity.
=> Avoid giving impression that it is legal to add stuff to ArborX::

src/details/ArborX_AccessTraits.hpp, src/details/ArborX_DetailsConcepts.hpp, test/tstDetailsConcepts.cpp
Rational: The traits have been unused for a long time and I don't anticipate we will change our mind anytime soon.
* Besides not being used, `is_expandable` and `has_centroid` functionality can easily be implemented using the detection idiom.
* `is_complete` had other issues that led to our using another mechanism to detect whether the access traits were specialized. https://github.com/arborx/ArborX/blob/b020ca71f3994d9bc8c0c3b151dceb41114061e3/src/details/ArborX_AccessTraits.hpp#L35
=> Drop unused type traits

src/ArborX_LinearBVH.hpp, src/details/ArborX_Box.hpp, src/details/ArborX_DetailsAlgorithms.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsKokkosExtAccessibilityTraits.hpp, src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp, src/details/ArborX_DetailsKokkosExtMathFunctions.hpp, src/details/ArborX_DetailsKokkosExtMinMaxOperations.hpp, src/details/ArborX_DetailsMortonCode.hpp, src/details/ArborX_DetailsNode.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, src/details/ArborX_Ray.hpp, test/ArborX_BoostRTreeHelpers.hpp, test/ArborX_EnableViewComparison.hpp, test/Search_UnitTestHelpers.hpp
Motivation: While profiling the compilation of some of our executables, I realized `<ArborX_Box.hpp>` was including the whole `<Kokkos_Core.hpp>` which is really silly. This PR is not attempting to fix all the defects, it specifically resolves that issue by breaking out the header `<ArborX_DetailsKokkosExt.hpp>` into
* `ArborX_DetailsKokkosExtAccessibilityTraits.hpp`
* `ArborX_DetailsKokkosExtArithmeticTraits.hpp` (which eventually will be replaced by Kokkos numeric traits)
* `ArborX_DetailsKokkosExtMathFunctions.hpp` (which eventually will be replaced by the math functions in `Kokkos::`)
* `ArborX_DetailsKokkosExtMinMaxOperations.hpp` (replaced by `std:{min,max}` if NVCC quits requiring an experimental flag to enable)
=> Breakout KokkosExt header and partial cleanup of includes

examples/dbscan/dbscan.cpp, src/details/ArborX_DetailsOperatorFunctionObjects.hpp, src/details/ArborX_DetailsPriorityQueue.hpp
Rational: It somehow bothered me when we had to include `<ArborX_DetailsPriorityQueue.hpp>` to use `Less` in #453 
Note that I made the operators `constexpr` to be consistent with the function objects in `<functional>`
=> Move comparison function objects out of priority queue header

test/CMakeLists.txt, test/tstQueryTreeCallbacks.cpp, test/tstQueryTreeComparisonWithBoost.cpp, test/tstQueryTreeDegenerate.cpp, test/tstQueryTreeManufacturedSolution.cpp
Incremental step to cleanup the unit test
* Renamed query tree executable
* Separated out spatial and nearest predicates in unit tests
* Updated more tests to use the tree traits
=> Query tree unit test (partial) cleanup

src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_Predicates.hpp, test/CMakeLists.txt, test/tstDetailsTypeRequirements.cpp
Rational:  These changes enable defining `kDOP` from #386 in an `Experimental::` namespace if we chose to do so.  Similarly they enable predicates such as `Ray` to be defined in user code.
You'll notice some oddities such as our requiring both `BoundingVolume::operator+=(Primitive)` and `expand(BoundingVolume, Primitive)` but the goal of this PR is only clarify the requirements and enable the use of types not defined within `ArborX::` (in particular remove the need to inject code in `ArborX::Details::`)
=> Clarify bounding volume and predicate geometry type requirements

test/tstQueryTreeComparisonWithBoost.cpp, test/tstQueryTreeManufacturedSolution.cpp
The comparison with Boost was removed in bfa54105cd4b8c84566c2adaa9f5f4cb4097e142 and never restored. The rest were part of #442 that were never merged.
=> Restore expected failures decorators for HIP

test/CMakeLists.txt
Note that CMake 3.18 introduces
```cmake
file(CONFIGURE OUTPUT <output-file> CONTENT <content> [...])
```
=> Avoid unnecessary rebuilds for generated unit test source files

scripts/benchmark.py, scripts/benchmark_plot.py, scripts/requirements.txt
This is a reduced version of @aprokop's script used for the paper. The intent here is that we can pass any kind of (partial) results produced by `benchmarks/bvh_driver/ArborX_BoundingVolumeHierarchy.exe` and display them graphically. At the moment, we print the mean with some error base indicating a transformed confidence interval for the rate with which points are processed.
Optionally, the actually numbers are also printed. Sample output:
[
](url)
Feel free to comment on how to improve it.
=> Add plotting script for benchmark

test/CMakeLists.txt, test/tstCompileOnlyAccessTraits.cpp, test/tstCompileOnlyCallbacks.cpp, test/tstCompileOnlyConcepts.cpp, test/tstCompileOnlyMain.cpp, test/tstCompileOnlyTypeRequirements.cpp
Rational: reduce the number of CMake targets in the project and organize unit tests a bit better
=> Merge all compile-only unit tests into a single executable

test/tstKokkosToolsAnnotations.cpp, test/tstKokkosToolsDistributedAnnotations.cpp
Use `BOOST_TEST_MESSAGE` instead of printing to the standard outpout.
One can pass `--log_level=message` to get the verbose output.
=> Avoid cluttering the console log in annotations tests

test/ArborXTest_TreeTypeTraits.hpp, test/Search_UnitTestHelpers.hpp, test/tstQueryTreeCallbacks.cpp, test/tstQueryTreeComparisonWithBoost.cpp, test/tstQueryTreeDegenerate.cpp, test/tstQueryTreeManufacturedSolution.cpp, test/tstQueryTreeTraversalPolicy.cpp
Fixing up typo in the copyrights and a few unnecessary header includes spotted on the kDOP PR
=> Cleanup query tree unit tests

src/details/ArborX_DetailsAlgorithms.hpp, test/tstBoostGeometryAdapters.cpp, test/tstDetailsAlgorithms.cpp
The goal of these changes is better alignment with Boost.Geometry
What motivated looking into this was a discussion on the kDOP PR that `isValid(Box{})` was returning `true` which we agreed was surprising.
There was no clear agreement on what should return `isValid(Box{p, p})`.  I propose we follow [Boost.Geometry](https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/algorithms/is_valid/is_valid_2_with_failure_value.html) for now and revisit later if needs to be.
=> Fixup isValid(Box) geometry algorithm

examples/dbscan/ArborX_DBSCAN.hpp, examples/dbscan/ArborX_DetailsDBSCANCallback.hpp, examples/dbscan/ArborX_DetailsDBSCANVerification.hpp, examples/dbscan/dbscan.cpp
Trying to align DBSCAN API with [Python DBSCAN package](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html) and [R DBSCAN package](https://cran.r-project.org/web/packages/dbscan/index.html). The goal is to simplify the main `dbscan()` call API, and allow to easily extend its functionality.
- Main `dbscan` call signature was aligned more with other implementations
- A new `DBSCAN::Parameters` was introduced to expand functionality later
- Main `dbscan` call now returns labels
This is similar to dbscan implementations in Python and R
- Verify was moved out of the main dbscan call
- Computing cluster CRS graph was now moved into the main file
It is unclear whether that's the final form, but as it is unknown, it
should not live in ArborX space right now
- Noise is …
=> Change API and reorganize DBSCAN structure

CMakeLists.txt, docker/Dockerfile, docker/Dockerfile.pgi
Per our discussion at the developers meeting.
Kokkos also [requires 3.16 as the minimum version](https://github.com/kokkos/kokkos/blob/897b79da51c1719b620990de4eabba154094bffe/CMakeLists.txt#L75) and I would like several features that are only available from that version (target-dependent generator expression in `add_test`, support for faster builds, etc.)
=> Require CMake 3.16

docker/Dockerfile.sycl
CI in https://github.com/arborx/ArborX/pull/486 fails since the SYCL compiler can't be built. We had the same problem in Kokkos and using this newer version helped to fix it.
=> Update SYCL in CI to fix building the compiler

examples/dbscan/dbscan.cpp
- Sampling
Allows to select a random subset of the read in set. The random nature allows to preserve the basis characteristics, while the sample size allows to control the size. Useful for comparison with other codes that are unable to run full datasets, or to perform scaling studies on a single dataset. The caveat is that typically increasing sampling increases density.
- Saving labels
Saving labels allows to later visualize the clustering results if given together with the data file.
=> Adding couple features to DBSCAN cmd line interface

src/details/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp, test/tstQueryTreeComparisonWithBoost.cpp
This adds Box-Box distance and add a test to check that it works: the implementation of `boost_rtree_nearest_predicate` has been moved to a function templated on the geometry (`ArborX::Point` or `Arborx::Box`).
=> Add Box-Box distance for Nearest query

src/details/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp
We need this to use Nearest with Sphere. Right now we can only use Sphere with Intersect.
=> Compute distance sphere-box

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
Distributed benchmark tends to time out on the PGI build. As there is no good reason why we need to make it this large, this PR reduces the sizes in the default configuration with the hope to reduce the number of failures.
=> Reduce default problem size for the distributed benchmark

src/details/ArborX_DetailsDBSCANCallback.hpp
The logic is not strictly necessary, and does not really bring any
performance gains. It also interferes with implementing other
algorithms, like pair traversal and dense box. So, let's just remove it.
=> Remove "fast" label initialization

examples/dbscan/CMakeLists.txt, examples/dbscan/converter.cpp, examples/dbscan/dbscan.cpp
I'm opening this PR mainly for a discussion on the topic, and deciding on the way to proceed.
Essentially, there are two (independent) issues I'd like to address.
1. Change the structure of a binary file read by DBSCAN driver
Currently, the binary reader expects the file to be "nxxxx...xy.....yz....z". Instead, I would prefer changing it to "ndxyzxyzxyz..." where "d" is the dimension of the dataset. The main reason is that it is sometimes useful to try running experiments with just a small portion of the datafile. The new approach allows to avoid reading the full file in, resulting in a much faster load times. It also simplifies reading data in, as we no longer need temporary arrays to store individual coordinates before assembling. Finally, adding dimension would allow us to work with …
=> Add data converters for DBSCAN

examples/dbscan/converter.cpp
Never noticed these because if SYCL or PGI fail, one have to actually remember to check the warnings.
=> Fix clang-tidy warnings in the converter

docker/Dockerfile.sycl
We should test with the new release and since there is a lot that has changed for for `SYCL`, this seems to be a good candidate.
=> Use Kokkos 3.4 for SYCL

src/details/ArborX_DetailsDBSCANCallback.hpp, src/details/ArborX_DetailsUnionFind.hpp
I am getting a bunch of warnings using rocm 4.2. hipcc wants `{}` around labels.
```
/home/users/ArborX/src/ArborX_DBSCAN.hpp:199:19: warning: suggest braces around initialization of subobject [-Wmissing-braces]
labels, CorePoints{num_neigh, core_min_size}});
^~~~~~ 
{     }
```
=> Fix warnings from hipcc

examples/raytracing/example_raytracing.cpp, src/details/ArborX_Ray.hpp, test/tstRay.cpp
Rational: I had taken a shortcut when I aliased `Vector` to `Point` and now actually regret it as I look into ray-triangle intersection
Note that I intentionally omitted conversion to and from `Point`.
@wjge please review
=> Let abstraction for Euclidean vector be strongly typed

benchmarks/point_clouds/point_clouds.hpp, examples/viz/tree_visualization.cpp, src/details/ArborX_DetailsKokkosExtAccessibilityTraits.hpp, test/ArborX_BoostRangeAdapters.hpp
Rational: `Kokkos::Impl:: SpaceAccessibility ` is being marked as deprecated.  One is suppose to use `Kokkos:: SpaceAccessibility` instead (https://github.com/kokkos/kokkos/pull/3978).  As I was making sure we are not using it, I discovered we were using `Kokkos::Impl::MemorySpaceAccess` and we should not do that.
=> Fixup Kokkos space accessibility checks

src/details/ArborX_Ray.hpp
#502 introduced a hidden error for gcc:
```
../src/details/ArborX_Ray.hpp:120:61: error: declaration of ‘using Vector = struct ArborX::Experimental::Vector’ [-fpermissive]
using Vector [[deprecated]] = ArborX::Experimental::Vector;
^
../src/details/ArborX_Ray.hpp:30:8: error: changes meaning of ‘Vector’ from ‘struct ArborX::Experimental::Vector’ [-fpermissive]
struct Vector : private Point
^~~~~~
```
=> Fix build error when using Vector inside Ray

.jenkins, docker/Dockerfile.hipcc
With this PR the tests can pass on MI60 and MI100. There is a way to make this nicer but we need to wait for @dalg24 to come back because I don't have access to `lascaux01`.
=> Add support for MI 100 in CI

CMakeLists.txt, examples/CMakeLists.txt
We don't export the version in a way that's useful for CMake, i.e., `find_package(ArborX 1.0)` does not work. This PR fixes that. We need to decide what kind of compatibility we want. Currently if you require 1.1, 1.2 will work but 2.0 won't.
=> Add and install ArborXConfigVersion.cmake

.jenkins, docker/Dockerfile.hipcc, test/tstQueryTreeComparisonWithBoost.cpp, test/tstQueryTreeManufacturedSolution.cpp
ROCm 4.1 fixes a lot of register of spills. Let's see if that fixes the CI
=> Update CI to ROCm 4.2

docker/Dockerfile.hipcc
I have update lascaux01 and lascaux01bis so the temporary variable is not necessary anymore.
=> Remove unnecessary variable in HIP Dockerfile

examples/dbscan/ArborX_DBSCANVerification.hpp, src/ArborX_DBSCAN.hpp, test/tstDBSCAN.cpp
Situation: a core point is connected to only boundary points. However,
those boundary are connected to other core points. So it may happen that
the boundary points are assigned to other clusters, resulting in a
cluster with a single point (core).
The bug was that those single core clusters were marked as noise.
The fix is ugly as heck, but I don't know how to do better.
=> Fix a subtle bug in DBSCAN noise marking

examples/dbscan/ArborX_DBSCANVerification.hpp, src/details/ArborX_DetailsFDBSCAN.hpp, test/tstHeapOperations.cpp
🤦‍♂️ 
Border is the correct name, not sure where I came up with boundary.
Per Ester et al '96 paper:
```
[snip] there are two kinds of points in a cluster, 
points inside of the cluster (core points) and
points on the border of the cluster (border points).
```
=> Rename "boundary" to "border" in DBSCAN

examples/dbscan/dbscan.cpp
This is useful for reproducibility in subtle sitations when a core point
may be stripped of all its border points, resulting in a cluster
consisting of a single core point. As this is triggered by different
algorithms and runs, it makes it challenging to compare the results
based on the number of clusters and the number of points in them.
=> Reduce default value of cluster_min_size in DBSCAN to 1

src/ArborX_DBSCAN.hpp
In most situations, it is faster than FDBSCAN.
=> Change default DBSCAN implementation to FDBSCAN-DenseBox

docker/Dockerfile, docker/Dockerfile.hipcc, docker/Dockerfile.pgi, docker/Dockerfile.sycl
The warning we are getting looks like this:
```
debugger.cpp:165:11: warning: ignoring return value of 'int
fscanf(FILE*, const char*, ...)', declared with attribute
warn_unused_result [-Wunused-result]
fscanf( in, "%d", &len );
~~~~~~^~~~~~~~~~~~~~~~~~
```
It is coming from the command
```
./bootstrash.sh <args>
```
and file `boost/tools/build/src/engine/debugger.cpp`.
=> Add -w flag to ignore in Boost build of b2

src/details/ArborX_DetailsFDBSCAN.hpp
FDBSCAN-DenseBox implemented a feature where the border points are
ignored. This turned out to be really important in situations where there are few core points.
This is porting back of that feature.
=> Update FDBSCAN to use algorithm from FDBSCAN-DenseBox for single points

CONTRIBUTING.md
The purpose of the PR is two-fold:
- Point contributors to the wiki
- Avoid confusion about the specific version of clang-format to use (Wiki contains the exact version, 7)
=> Update contributing to point to ArborX style in wiki

benchmarks/bvh_driver/benchmark_registration.hpp, benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, examples/dbscan/ArborX_DBSCANVerification.hpp, examples/dbscan/dbscan.cpp, examples/raytracing/example_raytracing.cpp, src/ArborX_BruteForce.hpp, src/ArborX_DBSCAN.hpp, src/ArborX_DistributedTree.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsUtils.hpp, test/tstDetailsCrsGraphWrapperImpl.cpp, test/tstQueryTreeCallbacks.cpp
`Kokkos::ViewAllocateWithoutInitializing` was deprecated in https://github.com/kokkos/kokkos/pull/4155.
=> Replace deprecated Kokkos::ViewAllocateWithoutInitializing

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, benchmarks/execution_space_instances/execution_space_instances_driver.cpp
Fixes the compiler warnings in https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-540/2/clang-tidy/#categoryContent (https://github.com/arborx/ArborX/pull/540).
=> Fix compiler warnings

docker/Dockerfile.sycl
Caused failure in #539 
Key is already present in the keydump so we don't need to retrieve it from the server.  This was an oversight, all other images had already been updated.
=> Fixup do not attempt to retrieve gpg key in SYCL image

src/details/ArborX_DetailsUtils.hpp
In https://github.com/arborx/ArborX/pull/538, it turned out to be useful to avoid allocating memory in `reallocWithoutInitializing` when the sizes already fit allowing to resize `Kokkos::Views` used in `query` beforehand and thus avoiding some synchronizations.
=> Check View sizes in reallocWithoutInitializing

src/details/ArborX_Ray.hpp
Compute the norm of the direction of the `Ray` using `double`. I have also removed the `Scalar` definition in `Ray` because it is not used anymore.
=> Use double to normalize Ray direction

examples/dbscan/dbscan.cpp
I still don't understand the reason why previous version did not work. When reading in 2D points, it was completely wrong, and resulted in uninitialized values, caught by valgrind.
=> Fix text reader in DBSCAN

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsKokkosExtScopedProfileRegion.hpp, test/CMakeLists.txt, test/tstScopedProfileRegion.cpp
Motivation: Calling `Kokkos::Profiling::popRegion()` at all the right places can be tedious and error-prone.  I ran into issues while using Kokkos tools on some ongoing work (HDBSCAN).
NOTE: I changed `<ArborX_LinearBVH.hpp>` to illustrate how one would guard profiling regions, I am not suggesting we absolutely should use the utility everywhere
=> Add scope-based profiling region utility

examples/dbscan/dbscan.cpp
DBSCAN example exit status indicated success regardless of whether the verification passes or not.
The changes I suggest ensure that failure will be observable from running ctest.
=> Fix exit status of the dbscan example

.jenkins/nightly.groovy
At the moment adding only one CUDA build against Kokkos develop branch
NOTE: Boost from the system package manager is version 1.71 which yields error with NVCC when enabling the tests .
=> Add Jenkinsfile for nightly builds

.jenkins/nightly.groovy
Fixup for #569 
I realized late we were building the examples twice instead of first examples and then benchmarks.
=> Fixup run benchmarks in the nightly build

src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp
Also alias to Kokkos numeric traits when available
=> Ignore cv qualifiers in arithmetic traits 

src/details/ArborX_Ray.hpp
* Drop backward compatibility `Ray::Vector` member type
* Let `Ray::{norm,normalize}` member functions be private
=> Cleanup `Experimental::Ray`

src/details/ArborX_DetailsKokkosExtSwap.hpp, src/details/ArborX_Ray.hpp, test/tstRay.cpp
Introduce `intersection(Ray, {Box,Sphere}, float&, float&} -> bool` functions.
The return value indicates whether the ray intersects with the geometry.  The trailing (output) parameters `tmin` and `tmax` provide the entry and exit point of the ray.
This is still a work in progress but I'd like feedback on the intent.
=> Refactor ray-box and ray-sphere intersection algorithms

src/details/ArborX_DetailsHappyTreeFriends.hpp
=> Return getBoundingVolume by value to work around HIP optimizer

src/details/ArborX_DetailsTreeConstruction.hpp
Fix #574 
~~Only a draft because current solution does not play well with #575~~
nevermind it does not use `HappyTreeFriends::getBoundingVolume`
=> Bugfix bounding volume accesses in generate hierarchy

benchmarks/bvh_driver/benchmark_registration.hpp, benchmarks/execution_space_instances/execution_space_instances_driver.cpp, examples/dbscan/dbscan.cpp, examples/raytracing/example_raytracing.cpp, src/ArborX_DBSCAN.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsFDBSCAN.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp
- Replace `atomic_fetch_[op]` with `atomic_[op]` when return value is not
used
- Replace `atomic_add(&ptr, 1)` with `atomic_increment(&ptr)`
The performance check on Ascent showed no difference for Cuda and Serial, and speedup for OpenMP (which I don't trust on Ascent).
=> Clean up atomics calls

benchmarks/bvh_driver/bvh_driver.cpp, benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, examples/dbscan/dbscan.cpp, examples/molecular_dynamics/example_molecular_dynamics.cpp, examples/raytracing/example_raytracing.cpp, src/details/ArborX_KokkosExtVersion.hpp
When testing out different combinations in #579, I had to switch between multiple Kokkos versions. It occurred to me that it was impossible to figure out which Kokkos version was used just from the log files.
This patch introduces a new function, `kokkosVersion()` in `ArborX::Details` so that we can use it for saving that information. The implementation is taken from `Kokkos::Impl::<anonymous namespace>::version_string_from_int()` which we can't use.
The output looks like this:
```
ArborX version    : 1.2 (dev)
ArborX hash       : febd2b03-dirty
Kokkos version    : 3.4.1
```
The only thing I'm not certain is where this function should leave. I'm sure @dalg24 has strong opinions on that.
I would have liked to also know the Kokkos hash, but I did not find it in Kokkos.
=> Print kokkos version in performance drivers

.jenkins/continuous.groovy
This should avoid us seeing warnings related to `-Wno-unknown-cuda-version`.
=> Silence warning in SYCL backend for unknown CUDA version in installed version

src/details/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp
I've been using this for a while when testing different things. It makes sense to add it to the master.
=> Add intersects(Sphere, Point) and intersects(Point, Sphere)

src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsUtils.hpp
We are not allowed to reach into the `Kokkos::Impl::` namespace.
Note that we could also use combined reducers.
=> Do not use `Kokkos::Impl::min_max_functor`

test/tstQueryTreeManufacturedSolution.cpp
When increasing the problem size from 11^3 to 51^3 in the manufactured
solution test, it failed:
```
../test/tstQueryTreeManufacturedSolution.cpp(254):
error: in "ManufacturedSolution/structured_grid<TreeExecutionAndMemorySpaces<ArborX__BoundingVolumeHierarchy, Kokkos__Device<Kokkos__Serial, Kokkos__HostSpace> >>":
check query(ExecutionSpace{}, tree, queries) == (make_reference_solution(indices_ref, offset_ref)) has failed
Mismatch at position 107186: ( 85094 87695 ) != ( 85094 ).
Mismatch at position 111824: ( 122546 125147 ) != ( 122546 ).
```
A query could find multiple points if the query box was aligned with one
of the grid lines, or close to it.
This patch changes the way we generate the random queries to make sure
each query does not get too close to a grid line, thus guaranteeing …
=> Fix an issue in the query test using manufactured solution

.gitlab-ci.yml
Since we require a newer Kokkos release, we also need to update the GitLab performance regression tests to keep the running.
=> Use Kokkos 3.4.01 in GitLab CI

src/ArborX_DistributedTree.hpp
Cleanup of #174. In the past couple years we had several developments that make this easy to implement. So might as well finish it.
I decided to not force push in #174, so that we can compare the PRs.
=> Use CUDA-aware MPI in DistributedTree constructor

src/details/ArborX_DetailsUtils.hpp
This allows function to work when only `operator<()` is provided.
=> Avoid using > comparison in min_max calculations

CMakeLists.txt
Following the suggestion in [this](https://github.com/arborx/ArborX/pull/608#issuecomment-1002750103) comment.
=> Print Kokkos version during configuration

.jenkins/continuous.groovy, docker/Dockerfile.sycl, examples/callback/example_callback.cpp, examples/dbscan/ArborX_DBSCANVerification.hpp
=> Update SYCL compiler and remove printf guarding with SYCL

.jenkins/continuous.groovy
I just realized this is now supported for Multibranch Pipeline and our server has a recent enough version of the plugins.
https://issues.jenkins.io/browse/JENKINS-43353
This will cancel previous builds of your PR if you push to the branch.  I am not quite sure if it disallow testing two different PRs at the same time but this is fine.
=> Cancel previous CI builds when changes are pushed to the branch

examples/callback/example_callback.cpp, examples/dbscan/ArborX_DBSCANVerification.hpp
This reverts commit d54e117fc0b7b6a6a36a4e1df0f66f58a244dc49 (part of #614). Corresponding to https://github.com/kokkos/kokkos/pull/4732.
=> Revert "Remove __SYCL_DEVICE_ONLY__ guards for ptintf"

src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsMutualReachabilityDistance.hpp, src/details/ArborX_MinimumSpanningTree.hpp, test/CMakeLists.txt, test/tstCompileOnlyCallbacks.cpp, test/tstDetailsAlgorithms.cpp, test/tstMinimumSpanningTree.cpp
Related to #557 
This version uses Andrey's kernels to compute the first neighbor (using a shared radius) and to update labels.
It was slightly changed to avoid allocating and deallocating arrays and do the computation with permuted indices with a finalization step to revert back to original indices.
=> Add facility to compute the minimum spanning tree

src/details/ArborX_DetailsMortonCode.hpp
Introduced in #635.
We do (1 << 31). The problem is that MAX_INT (which is 2147483647) is one smaller than that, which leads to overflow.
NVCC correctly warns about that. But we don't catch Nvidia warnings in CI (see #272), so we missed this.
Not sure why none of the host compilers produced a warning.
This is the only place where it is necessary, all other places shift by less than 31.
This bug potentially leads to construction of a wrong hierarchy.
=> Fix a warning for 64-bit 2D Morton codes

examples/dbscan/dbscan.cpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributor.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsKokkosExtViewHelpers.hpp, src/details/ArborX_DetailsSortUtils.hpp, src/details/ArborX_DetailsUtils.hpp, src/details/ArborX_MinimumSpanningTree.hpp, test/tstDetailsCrsGraphWrapperImpl.cpp, test/tstDistributedTree.cpp, test/tstQueryTreeCallbacks.cpp, test/tstQueryTreeTraversalPolicy.cpp
=> Move view helpers `ArborX:: -> KokkosExt::` and pass execution space instance

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, test/tstDetailsTreeConstruction.cpp
ArborX is unable to run GeoLife (https://www.microsoft.com/en-us/research/publication/geolife-gps-trajectory-dataset-user-guide/) dataset in any reasonable manner (i.e., it takes hundreds of seconds to find a closest neighbor for this 24M problem). The problem is that hundreds of thousands of points are assigned the same Morton index. As we just "randomly" combine such pairs during the hierarchy construction, it leads to dramatic overlap in the bounding volumes for the lowest levels.
I have checked the number of duplicate codes and their distribution for two 3D datasets: HACC and GeoLife (those are the ones I had readily available).
"# M codes (>3 reps)": number of Morton codes that have more than 3 duplicates, i.e. number of Morton grid cells with more than 3 points in them
"# points …
=> Use 64-bit Morton indices by default in the BVH construction

src/details/ArborX_DetailsTreeNodeLabeling.hpp
`Details::initLabels` was used in earlier versions of our computing minimum spanning trees but we don't use it any more and there is no plan to do so.
=> Remove unused node labeling utility

src/ArborX_DBSCAN.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsUtils.hpp, test/tstDetailsUtils.cpp
This utility is general enough to be used beyond DBSCAN.
=> Move computing offsets in a sorted view to general utilities and add a test

examples/viz/tree_visualization.cpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBruteForceImpl.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsMortonCode.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_SpaceFillingCurves.hpp, test/tstDetailsTreeConstruction.cpp
Per discussion on #637 enable using 32-bit Morton codes
=> Enable alternate projection onto space filling curve

src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsKokkosExtMathFunctions.hpp, test/Search_UnitTestHelpers.hpp, test/tstDistributedTree.cpp
Currently, ArborX does not compile if you want to use nearest neighbors on anything but `Point`. The problem is that we get the `Geometry` of the queries to build a sphere but we assume that the `Geometry` is a `Point` that we can use as the center of the sphere. This functions add three `buildSphere` functions that create a sphere if the `Geometry` is a `Point`, a `Box`, or a `Sphere`.
=> Fix bugs in nearest search in DistributedTree

.jenkins/continuous.groovy
Comparing https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/ArborX/detail/PR-654/7/pipeline and https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/ArborX/detail/PR-654/6/pipeline, this seems to accelerate build and run time significantly:
build: 35m 39s -> 19m 23s
test: 6m 57s -> 1m 24s
=> SYCL: Use device-code-split=per_kernel

.jenkins/continuous.groovy
I observed recently a couple builds hanging for 10+ hrs and that I had to kill by hand.
Here I propose to set a limit at 2hrs.  The limit is for individual stages.  We could pick something shorter but I think that anything above 2hrs might as well get killed.
=> Set timeout on Jenkins CI builds

.jenkins/continuous.groovy
I have seen multiple times that the CI timed out for SYCL when rebuilding the container. The overall run should run around 2h including building the compiler which is right on the limit for our current setting. Using 3h should provide a safe margin.
=> Increase timeout in CI from 2h to 3h

src/details/ArborX_MinimumSpanningTree.hpp, test/CMakeLists.txt, test/tstCompileOnlyWeightedEdges.cpp, test/tstMinimumSpanningTree.cpp
Variation on #660
As in the original PR by Andrey, the performance improvement comes from introducing an intermediate array that stores the weights, and taking advantage of lock-free atomics when searching for the component nearest neighbors.
Suggested improvements in this PR include
* smaller increase in memory footprint (allocate `View<float*>` instead of `View<WeightedEdge*>`)
* avoid allocating and deallocating at each iteration step
* one extra kernel  launch instead of three
* faster edge comparison through using `long`
=> Improve MST performance by prefering lock-free atomics

src/ArborX_CrsGraphWrapper.hpp, src/details/ArborX_AccessTraits.hpp, test/tstCompileOnlyAccessTraits.cpp
Fix #399.
To be merged after releasing 1.2. Will affect platoanalyze if platoengine/platoanalyze#101 not merged there.
=> Issue an error when using old Traits::Access

.jenkins/continuous.groovy
We had changed `-DKokkos_ENABLE_{PTHREAD -> THREADS}` in the Clang+CUDA build but that renaming did only happen in Kokkos 3.6
=> Fixup re-enable Threads backend testing that was accidentally disabled

.jenkins/continuous.groovy, docker/Dockerfile, docker/Dockerfile.hipcc, docker/Dockerfile.sycl
CMake 3.18.5 -> 3.22.4
Boost 1.72.0 -> 1.79.0
Google Benmchark 1.5.0 -> 1.6.1
=> Update HIP CI build ROCm 4.2 -> 5.0

benchmarks/bvh_driver/benchmark_registration.hpp
Warning:
```
<arborx>/src/details/ArborX_DetailsPermutedData.hpp(44): warning:
calling a __host__ function from a __host__ __device__ function is not allowed
```
=> Mark one AccessTraits size() as KOKKOS_FUNCTION

src/ArborX_LinearBVH.hpp
I see up to 10% faster results for our performance benchmark and around 17% for DBScan.
=> Use ropes for all backends

examples/viz/tree_visualization.cpp
Rational: it is likely going to be deprecated
=> Avoid `Kokkos::InitArguments` struct

test/ArborX_EnableViewComparison.hpp
[arborx/ArborX@`a4e33e3` (#683)](https://github.com/arborx/ArborX/pull/683/commits/a4e33e37045fdbdfd53695a7715f755e8c794b64) exposed that we can't use subviews in `BOOST_TEST` macros since they are strided and, thus, its elements are potentially not contiguous in memory.
=> Restrict ViewComparison to non-strided Views

examples/dbscan/dbscan.cpp
I find it useful in certain situation to just print noise instead of requiring a user to do the calculations.
=> Print out the number of noise points in the DBSCAN driver

benchmarks/point_clouds/point_clouds.hpp
The original code normalized a uniformly distributed point to produce a
point on a sphere. However, this does not result in the uniformly
distributed points on the sphere itself. The density of the regions
point to the box corners would be higher than that towards centers of
the box faces.
Using standard normal distribution, however, will. To see this,
$$f(x) = \frac{1}{\sqrt{2\pi}} e^{-\frac12 x^2}$$
which results in
$$f(x,y,z) = \frac{1}{(2\pi)^{\frac32}} e^{-\frac12(x^2+y^2+z^2)}$$
which only depends on the magnitude but not any direction.
=> Fix generation of the hollow sphere point cloud to be u.a.r.

src/ArborX_LinearBVH.hpp
It has been broken for 1.5 years since 5355a8e. The introduction of the
BoundingVolume template argument in that pull request did not update the
device type specialization which led to no match when trying to use one. Given that, it should be safe to remove it.
I see two uses of `ArborX::BVH<DeviceType>` on GitHub.
- [lgrtk](https://github.com/sandialabs/lgrtk/blob/d969e670b9ba4371ae74b0cef023f7e887073fdd/otm_arborx_search_impl.cpp#L19)
I'm not sure if it's even used, or updated with a recent ArborX version (last code 13 months ago)
- [platoengine](https://github.com/platoengine/platoengine/blob/a869510744e48d2003953a48a094c12c00147e6f/base/src/PlatoSubproblemLibrary/Geometry/PSL_TetMeshUtilities.hpp#L179) (proposed fix: platoengine/platoengine#338)
The code in question is hidden behind …
=> Remove deprecated version of BVH templated on a device type

benchmarks/execution_space_instances/execution_space_instances_driver.cpp, examples/brute_force/brute_force.cpp, src/ArborX_DBSCAN.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, test/ArborX_BoostRTreeHelpers.hpp, test/Search_UnitTestHelpers.hpp, test/tstBoostGeometryAdapters.cpp, test/tstDetailsAlgorithms.cpp
Part of #708 that fixes missing includes.
=> Include missing headers (works now due to transitive includes in DetailsGeometry)

.jenkins/nightly.groovy
Anticipating change in Kokkos minimum requirement on the `develop` branch
Testing here https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/rocm52/detail/rocm52/1/pipeline/10
=> Bump ROCm 4.5.2 -> 5.2 in nightly builds

src/ArborX_BruteForce.hpp, test/CMakeLists.txt
This is in preparation to using brute force for multi-dimensional data.
Realistically, it's not really `BoundingVolume`, but rather some `Value`. But that can be changed with APIv2.
=> Template BruteForce on BoundingVolume

.clang-tidy, .jenkins/continuous.groovy, CMakeLists.txt, examples/dbscan/CMakeLists.txt, src/details/ArborX_DetailsTreeConstruction.hpp
I disabled several Clang-Tidy checks:
- modernize-use-no-discard
- modernize-use-concat-namespaces
- modernize-unary-static-assert
=> Require C++17 standard

docker/Dockerfile.sycl
- Update Kokkos to 3.7.00, not release but the latest release candidate branch
Will need to be updated after the release, but can't hold on waiting Kokkos 3.7 release any longer.
=> Update SYCL testing

src/details/ArborX_DetailsBruteForceImpl.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/geometry/ArborX_HyperBox.hpp
Alternative to #727 making sure that `reduction_identity<ArborX::Box>` is actually used.
=> Use Kokkos::Sum for Kokkos::parallel_reduce using Box and hyper Box

src/details/ArborX_DetailsSortUtils.hpp
=> #745: Pass through execution space argument in sorting

src/geometry/ArborX_Box.hpp, src/geometry/ArborX_HyperBox.hpp
... wherever appropriate
This is a draft.  We will need it if kokkos/kokkos#5450 gets merged
=> Forward compatibility include `<Kokkos_ReductionIdentity.hpp>` header

src/details/ArborX_MinimumSpanningTree.hpp
I realized that we never updated the code with the final state of the experiments we did for the paper. What we ended up was using shared radii only in Serial. In parallel, they were inconsistent, sometimes slower, sometimes faster than not using them. We decided not to describe them because of the complexity.
I propose leaving them in, but hardcode to the ones used in the paper. We could consider enabling a command line argument for switching them in the future.
=> Use shared radii during MST traversal only for Serial

src/details/ArborX_MinimumSpanningTree.hpp
A major oops! This made us use unitialized values in computing core distances, that sometimes affected results for `minPts > 1`.
This was originally caught by dumping MST and seeing some edge weights becomes things like `1e+25` or `1e+31`. Running `-fsanitize=undefined -fsanitize=memory` did not produce any leads. `valgrind` was also unhelpful pointing at places much later during execution. Tracked it by using early returns in the `MinimumSpanningTree` constructor.
@dalg24 We may need to create a golden test for `minPts > 1` so as not to repeat this. But I currently don't have time to do that. I'll just file an issue.
=> Initialize core distances in MST to zero to be used in Max functor

src/details/ArborX_DetailsCartesianGrid.hpp
For some problems and eps, FDBSCAN-DenseBox may suffer from severe loss
of precision when computing cellBox(). This may result in wrong DBSCAN
results.
Initially, the problem was observed on a full NGSIM dataset:
```
$ ./ArborX_DBSCAN.exe --binary \
--filename /data/data_and_logs/2021_02_20_dbscan_datasets/mustafa_2019/ngsim.arborx \
--print-dbscan-timers --core-min-size 2 --eps 1.0 --max-num-points 90000 \
--impl fdbscan-densebox --verify
<...>
Core point is marked as noise: 41888 [-1]
Core point is marked as noise: 17027 [-1]
Core point is marked as noise: 43104 [-1]
```
Tracking down the issue revealed that a point 2279 (part of a dense
cell) was finding point 10369 (not part of a dense cell), but the
reverse was not true (i.e., 10369 was not finding the dense cell that
2279 was in). …
=> Warn about loss of precision in FDBSCAN-DenseBox

src/details/ArborX_DetailsDistributor.hpp, test/tstKokkosToolsDistributedAnnotations.cpp
Noticed while trying to use DTK with Trilinos 14/Kokkos 3.7, also see https://github.com/ORNL-CEES/DataTransferKit/pull/603.
Our intent here was to initialize `dest_buffer` as empty first for general layouts. The default layout, e.g., for `LayoutLeft`, represents is 0-dimensional, though, see https://github.com/kokkos/kokkos/blob/25e2302a61cd07c8a5f8c369bbbcd2f43fde542f/core/src/Kokkos_Layout.hpp#L91-L100, and we started checking for the passed layout to have correct rank in Kokkos 3.7.0.
Since we are resizing the `View` in the next line anyway, it's easy to fix the issue here and just initialize it with the correct layout in the first place.
=> Fix View creation in do_posts_and_waits

examples/CMakeLists.txt, examples/dbscan/CMakeLists.txt, examples/dbscan/example_dbscan.cpp
In #736, the main DBSCAN driver was moved to the `benchmarks/`. It is still a good idea to have an example, so this is its replacement.
=> Add DBSCAN example

benchmarks/dbscan/data.hpp
Detected with `-Wpedantic`. Not sure how they creeped in.
=> Remove weird commas

src/details/ArborX_AccessTraits.hpp, test/tstCompileOnlyAccessTraits.cpp
Before that PR, the provided access traits for rank-2 views would always deduce `ArborX::Point`
```
Kokkos::View<float**> -> ArborX::Point
Kokkos::View<float*[3]> -> ArborX::Point // OK
Kokkos::View<float*[2]> -> ArborX::Point // Out of bound access at runtime
Kokkos::View<float*[5]> -> ArborX::Point // Last two dimensions discarded
```
In this PR I propose we deduce `ArborX::ExperimentalHyperGeometry::Point<DIM>` if the 2nd extent of the view (`DIM`) is known at compile time
```
Kokkos::View<float**> -> ArborX::Point // Unchanged
Kokkos::View<float*[3]> -> ArborX::ExperimentalHyperGeometry::Point<3>
Kokkos::View<float*[2]> -> ArborX::ExperimentalHyperGeometry::Point<2>
Kokkos::View<float*[5]> -> ArborX::ExperimentalHyperGeometry::Point<5>
```
=> Deduce point spatial dimension from view static extent

test/CMakeLists.txt, test/tstKokkosToolsAnnotations.cpp, test/tstKokkosToolsDistributedAnnotations.cpp
Following up on https://github.com/arborx/ArborX/pull/749#discussion_r998190756
* Print the label on failure instead of unconditionally adding it as a comment
* Prefer regular expressions instead of `isPrefixedWith` helper test function
=> Print on failure in kokkos tools annotations tests

src/ArborX_DBSCAN.hpp, src/details/ArborX_DetailsFDBSCAN.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsUnionFind.hpp
The patch tries to solve the problem of slow `Serial` atomics when Kokkos compiled with other backends. This patch is not strictly necessary right now, as one could compile Kokkos with just the `Serial` backend. However, it becomes necessary once I introduce a dendrogram construction algorithm using union-find, which will run MST construction on the device, but construct union-find on CPU using a single thread. In that context, it's not possible to fix it by just compiling Kokkos.
Drive-by change: `labels_` -> `_labels`
=> Add a faster implementation of the union-find for Serial

src/details/ArborX_DetailsUtils.hpp, test/tstDetailsUtils.cpp
Kinda embarrassing especially considering that we still haven't moved it out of `ArborX::`
=> Fix `min` and `max` algorithms for element types other than `int`

src/details/ArborX_Dendrogram.hpp, src/details/ArborX_DetailsDendrogram.hpp, src/details/ArborX_DetailsWeightedEdge.hpp, src/details/ArborX_MinimumSpanningTree.hpp, test/CMakeLists.txt, test/tstDendrogram.cpp
This PR introduced dendrogram construction. Dendrogram is a binary tree on $n$ vertices. We store this tree as a set of parents of size $2n-1$, with the first $n-1$ corresponding to internal nodes, and last $n$ to the original vertices.
This PR also does two additional changes:
- Move out `WeightedEdge` out of the minimum spanning tree header
=> Introduce dendrogram construction based on union-find

docker/Dockerfile.clang-format, scripts/check_format_cpp.sh, src/ArborX_DBSCAN.hpp, test/tstDistributedTree.cpp
The container for the Style did not have `git` installed. This resulted in the formatting script getting an empty set of cpp files, not performing any checks, and always passing.
=> Fix Style check in CI

src/details/ArborX_DetailsDistributedTreeImpl.hpp, test/tstDistributedTree.cpp
There is a problem when using `Ray` and `DistributedTree` together; we don't define a `get` function when the `Geometry` is a  `Ray`. This PR fixes the bug and add a test. I've also added a call to `Details::check_valid_access_traits` to make sure that  the `Predicate` we create make sense. Without it the error message is really obscure (you get an error about `Kokkos::nonesuch`...)
=> Fix a bug when using distributed tree with rays

src/details/ArborX_DetailsPermutedData.hpp
Right now, we unconditionally create an unnecessary copy of a query when using `PermutedData`. If the queries don't require attachments (for example, when using a pure callback), this unnecessarily creates a copy.
=> Fix return type in PermutedData with no attachment

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
When running ordered traversals with `CrsGraph`, it incorrectly printed `nearest` instead of `ordered_traversal` as a profiling region.
Drive-by change to use `constexpr` when labeling in `BVH`.
=> Fix incorrect profiling region naming in CrsGraph

docker/Dockerfile.hipcc
While working on #788, an issue came up. `hipcc` does not follow OpenMP standard and does not define `_OPENMP` (see [here](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_faq.md#why-_openmp-is-undefined-when-compiling-with--fopenmp)). So I think it would make sense to test OpenMP instead of Serial in the HIP build to catch related issues.
I chose to make the change inside the docker container and not inside of `.jenkins` as we only have one build running using that container, and I did not want to split Kokkos argument in two places.
=> Switch host in HIP testing from Serial to OpenMP

test/CMakeLists.txt
Workaround was in place for backward compatibility for Kokkos version less than 3.6 which is now our minimum required
=> Drop pre Kokkos 3.6 PTHREAD workaround

.gitlab-ci.yml
Fix https://github.com/arborx/ArborX/pull/799#discussion_r1058338594
It is only needed when building the Google benchmark unit tests which we don't do as we properly configure with `-DBENCHMARK_ENABLE_TESTING=OFF`
=> Do not bother with downloading GTest

test/tstMinimumSpanningTreeGoldenTest.cpp
Testing mrd based on the edges output is hard because many edges may have the same weight. Instead, we just test the total weight of the MST, and compare to the reference weight computed externally.
Fix #754.
=> Add testing for MST with mutual reachability metric

.gitlab-ci.yml, .jenkins/nightly.groovy, benchmarks/bvh_driver/CMakeLists.txt, benchmarks/bvh_driver/benchmark_registration.hpp, docker/Dockerfile.sycl
- Require benchmark 1.5.4
- Update our BVH benchmark to use new rate feature
- Update nightly containers to Ubuntu 22.04 
Still no way to require specific version of the benchmark in CMake, though. The main reason for the PR is to not propagate this rate issue to other benchmarks, such as union-find.
=> Require benchmark 1.5.4, update nightly containers to Ubuntu 22.04

src/ArborX_DistributedTree.hpp, src/details/ArborX_DetailsDendrogram.hpp, src/details/ArborX_DetailsDistributor.hpp, src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
Just like we annotate kernels, we should annotate our fences.
The `std::string` label argument is available since Kokkos 3.5
=> Annotate fences

benchmarks/CMakeLists.txt, benchmarks/bvh_driver/CMakeLists.txt
As we introduce more benchmarks that use Google Benchmark, it makes sense to move it to the common file.
=> Move Google benchmark detection to the common CMakeLists.txt

benchmarks/bvh_driver/CMakeLists.txt
See https://github.com/arborx/ArborX/pull/806#pullrequestreview-1232499529
=> Attempt to get rid of `find_package(Threads)` in BVH benchmark

src/details/ArborX_DetailsDendrogram.hpp
Allocate less memory (drop `permute` view) and launch 2 kernels less (`iota` and `permute_and_fill`)
Partially addressing https://github.com/arborx/ArborX/pull/797#issuecomment-1364547104
=> Cleanup `Details::dendrogramUnionFind()` and prefer `sortByKey()`

src/details/ArborX_DetailsHalfTraversal.hpp, test/CMakeLists.txt, test/tstDetailsHalfTraversal.cpp
Per https://github.com/arborx/ArborX/pull/801#issuecomment-1368134410
Fix #409.
=> Add specialized "half" tree traversal for spatial predicates

src/details/ArborX_DetailsExpandHalfToFull.hpp, test/CMakeLists.txt, test/boost_ext/CompressedStorageComparison.hpp, test/tstDetailsExpandHalfToFull.cpp
Per https://github.com/arborx/ArborX/pull/801#issuecomment-1368134410
=> Implement expand half to full (neighbor list)

src/details/ArborX_DetailsExpandHalfToFull.hpp
In #809 we had opted to merge in the version with `RangePolicy` even though it was commented out with a macro guard in the code I was using to measure performance.
I don't have numbers handy to share but with the `TeamPolicy` version, findHalfNeighborList+expandHalfToFull is 15% faster than the "classic" BVH query implementation, with a `RangePolicy` it is slower than the current status quo.
=> Use `TeamPolicy` in `Details::expandHalfToFull` to improve performance

benchmarks/CMakeLists.txt, benchmarks/union_find/CMakeLists.txt, benchmarks/union_find/union_find.cpp
This would allow to evaluate any changes in the union-find data structure.
=> Add union-find benchmark

src/details/ArborX_DetailsExpandHalfToFull.hpp, src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
From #812 
Essentially avoid creating temp views that duplicate labels from user-provided view and prefer giving them a meaningful name with the proper `ArborX::` prefix.
There might be more places where we can use it.  I only applied where I knew on top of my head it was needed.
=> Take optional label argument in `KokkosExt::clone[WithoutInitializingNorCopying]`

src/details/ArborX_NeighborList.hpp, test/CMakeLists.txt, test/tstNeighborList.cpp
Base on the new specialized "half" traversal from #808 
For reference, performance on AMD GPU for the MD example
```
BEGIN KOKKOS PROFILING REPORT:
TOTAL TIME: 0.814269 seconds
TOP-DOWN TIME TREE:
<average time> <percent of total time> <percent time in Kokkos> <percent MPI imbalance> <remainder> <kernels per second> <number of calls> <name> [type]
===================
|-> 2.78e-01 sec 34.1% 98.1% 0.0% 0.0% 6.48e+01 1 classic [region]
|   |-> 2.72e-01 sec 33.4% 99.3% 0.0% 0.0% 4.04e+01 1 ArborX::query [region]
|   |   |-> 2.72e-01 sec 33.4% 99.3% 0.0% 0.0% 4.04e+01 1 ArborX::CrsGraphWrapper::query::spatial [region]
|   |       |-> 2.70e-01 sec 33.2% 100.0% 0.0% 0.0% 2.96e+01 1 ArborX::CrsGraphWrapper::two_pass [region]
|   |       |   |-> 2.06e-01 sec 25.2% 100.0% 0.0% 0.0% 9.73e+00 1 …
```
=> Add new facility to find "half" or "full" neighbor lists

src/ArborX_DBSCAN.hpp
```
<snip>/arborx/src/ArborX_DBSCAN.hpp(66):
warning #20013-D: calling a constexpr __host__ function("operator __nv_bool") from a
__host__ __device__ function("operator()") is not allowed.
The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
```
=> Fix warning on CUDA

src/details/ArborX_DetailsNode.hpp
Lets not lie to ourselves that we support `size_t` here. We only support `unsigned`. 
I was hoping to also see some performance improvements for some backends, as `size_t` may be 8 bytes, but we already do an implicit case from `size_t` to `int` in the kNN when we define `PairIndexDistance` to be `Kokkos::pair<int, float>;`. The Ascent benchmark is [here](https://code.ornl.gov/ecpcitest/alexa/-/jobs/1462275).
So, realistically, this PR is mainly about making what's actually being done clearer, and avoid implicit conversion.
Note, that while it is possible to use `size_t` for the permutation indices in the `sortObjects`, it is still lying as we don't store `size_t` inside a `Node`, only `int`. In addition, recent patch hardcoded `unsigned` when using Kokkos in `sortByKey`, so it does not …
=> Do not use size_t for permutation indices in Node

.github/workflows/gitlab-ci.yml
Warning message from GitHub:
```
The ubuntu-18.04 environment is deprecated, consider switching to
ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details
see https://github.com/actions/virtual-environments/issues/6002
```
=> Update the container os for gitlab workflow to Ubuntu 22.04

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_PairIndexRank.hpp, test/ArborX_BoostRTreeHelpers.hpp, test/Search_UnitTestHelpers.hpp, test/boost_ext/ArborXPairIndexRankComparison.hpp, test/tstDistributedTree.cpp
Alternative to #816.
- Introduce `ArborX::IndexRankPair`
It does not make sense for users to define their own struct to receive the results of the default call to the distributed query
- Update testing to use it
=> Introduce ArborX::PairIndexRank

src/details/ArborX_DetailsHeap.hpp, test/tstMinimumSpanningTreeGoldenTest.cpp
I get warnings when compiling ArborX in release mode with g++ 11.2. I don't get any warnings in debug mode. The first commit is pretty uncontroversial, I am not sure if we want the second one. It looks like a false positive.
=> Fix warnings in release mode

benchmarks/dbscan/dbscan_timpl.hpp, src/details/ArborX_Dendrogram.hpp, src/details/ArborX_DetailsDendrogram.hpp
This is in preparation for integration of the new dendrogram routine.
The sort routine is going to be common for both, so I'm moving it to before the dispatch.
Also, this means that we don't need to pass parents heights to the dendrogram construction, making them weight-agnostic.
=> Move union-find dendrogram sorting to the main struct

benchmarks/dbscan/ArborX_DBSCANVerification.hpp, examples/callback/example_callback.cpp
This avoids some compiler errors on the testbeds that have already been reported.
=> Use sycl::ext::oneapi::experimenta::printf

src/details/ArborX_DetailsSortUtils.hpp
`View::Rank` just happens to work.  It is not even documented by Kokkos.  (I am considering whether it should be deprecated.)
Use `View::rank` instead (or View::rank() in later Kokkos versions, that is 4.1+)
=> Do not use `View::Rank`, prefer `View::rank`

src/details/ArborX_DetailsDistributedTreeImpl.hpp
We use `sendAcrossNetwork` multiple times, and it would be nice to distinguish the time taken by each.
As a drive-by change, switch function level region pushing to scoped regions.
=> Switch to using ScopedProfileRegion and append label in sendAcrossNetwork

src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/kokkos_ext/ArborX_DetailsKokkosExtClassLambda.hpp, test/tstDistributedTree.cpp, test/tstQueryTreeCallbacks.cpp
Requiring C++17, we can now resolve the comments mentioning "capture *this". Also, this shows that we forgot to update the GitLab CI. I would propose to always just build `Kokkos` for clarity.
edit: This pull request now uses a newly defined `ARBORX_CLASS_LAMBDA` instead.
=> Use KOKKOS_CLASS_LAMBDA via ARBORX_CLASS_LAMBDA

src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsUtils.hpp, test/tstDetailsDistributedTreeImpl.cpp
Creating layout right mirror view is done on the host for the non CUDA-aware MPI, so initialization was also done on the host, potentially slow.
Drive-by changes:
- Reorganize `create_layout_right_mirror_view` and `create_layout_right_mirror_view_and_copy` functions to switch to using constexpr as to not duplicate the logic
- Replace check `!LayoutStrided` by `LayoutLeft || Layout_Right`
=> Rename `create_layout_right_mirror_view{->_no_init}` which does not initialize

src/details/ArborX_DetailsTreeTraversal.hpp
Some indices may be in the heap only temporary, and not stay till the end. For those indices, there is no point in getting the correct leaf indices.
=> Delay getting correct leaf indices in nearest

test/CMakeLists.txt
=> Do not include the scoped profile test when using newer Kokkos

src/geometry/ArborX_DetailsAlgorithms.hpp
It is templated to support different types of boxes, not to avoid adding a volatile overload like in its original form.
=> Drop outdated comment in `expand<Box1, Box2>`

benchmarks/dbscan/data.hpp
Standard does not guarantee portability of `<random>`. While by some luck random engines are portable (except for the `default_random_engine`), `uniform_int_distribution` is not.
The problem is then that when we sample a dataset on different platforms/compilers, we get a different data. It is problematic for reproduciblity.
While it is possible to use something like boost random, I opted instead to use [Lehmer](https://en.wikipedia.org/wiki/Lehmer_random_number_generator) random generator in place, as it is fast, easy to implement, and does what we need.
=> Make data file sampling portable

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsHalfTraversal.hpp, src/details/ArborX_DetailsHappyTreeFriends.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeNodeLabeling.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, src/details/ArborX_MinimumSpanningTree.hpp, test/tstDetailsTreeConstruction.cpp, test/tstDetailsTreeNodeLabeling.cpp
This PR makes leaf nodes correspond to $[0, n)$ range, and internal nodes to $[n, 2n-1)$.
While working on #864, I realized that part of the reason why MST is so complex is that because our internal nodes are indexed first, and leaf nodes after. Swapping them around makes the complexity much more manageable by getting rid of all `<blah> - n + 1` calculations. It also aligns better with tree reduction from a given view corresponding to leaf node values.
I see no downside to swapping the ranges around.
=> Switch ranges for leaf and internal indices

.jenkins/continuous.groovy, docker/Dockerfile.sycl, test/tstMinimumSpanningTreeGoldenTest.cpp, test/tstQueryTreeCallbacks.cpp, test/tstQueryTreeRay.cpp
This pull request updates the SYCL compiler to 2023.0.0 which allows us to use Codeplay's CUDA plug-in (https://codeplay.com/solutions/oneapi/for-cuda/) with a public release which improves building the compiler.
Unfortunately, we are seeing some floating point issues with this that partly seem to result from math functions giving different results on host and device even after using `-fp-model=precise`.
The current pull request tries to address them by simply allowing bigger floating point tolerances for the affected tests.
=> Update SYCL docker container avoiding buiding the compiler

src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsHalfTraversal.hpp, src/details/ArborX_DetailsHappyTreeFriends.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_DetailsTreeVisualization.hpp, src/details/ArborX_MinimumSpanningTree.hpp
The goal of this PR is to separate the functions for leaf and internal nodes based on tags.
=> Separate HappyTreeFunctions for internal and leaf nodes

src/ArborX_DistributedTree.hpp, src/ArborX_LinearBVH.hpp
- `Enable` in `BasicBoundingVolumeHierarchy` could have been removed in #458
- `Enable` in `DistributedTree` could have been removed in #706
=> Remove Enable template parameter from BasicBoundingVolumeHierarchy and DistributedTree

CITATION.bib, README.md
GitHub will add "Cite this repository" link on the right once it detects the presence of the citation file. The documentation is [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files). I don't see a need to use CFF format yet, though it could make it a bit easier to cite in different formats.
=> Move citation details

src/geometry/ArborX_HyperPoint.hpp
Fix #883 
The default constructor prevents aggregate initialization.
=> Drop default constructor for the point hyper gerometry

CMakeLists.txt
This PR target the release 1.4 branch in order to create a new release 1.4.1. We first try to find Kokkos 3.7 or later. If that fails, we try to find Kokkos 4.0. Without this PR, ArborX 1.4 cannot be built using any release version of Trilinos .
=> Workaround to compile ArborX with Trilinos 14.0

src/details/ArborX_MinimumSpanningTree.hpp, src/kokkos_ext/ArborX_DetailsKokkosExtBitManipulation.hpp
We get warnings/errors on Cuda for `reinterpret_cast`
```
../src/details/ArborX_MinimumSpanningTree.hpp:615:70: error:
dereferencing type-punned pointer will break strict-aliasing rules
[-Werror=strict-aliasing]
```
I think we should temporarily (until requiring 4.1) provide `bit_cast`.
Not sure whether to add the tests. Implicitly tested through Boruvka dendrogram test.
=> Add KokkosExt::bit_cast

src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
This is in preparation to switching the callbacks in APIv2. It would reduce the number of places to change. It is also a shorter code.
=> Use constexpr instead of SFINAE in InsertGenerator

.gitlab-ci.yml
Right now, we install over the current installation. It usually works, but may result in issues when the install directory contains outdated headers. So, let's wipe the install directory out.
Case in point: installing 3.7 over 4.0 produces errors with `ReductionIdentity` when building ArborX:
```
/ccsopen/proj/csc333/kokkos.install/include/Kokkos_ReductionIdentity.hpp(81):
error: class "Kokkos::reduction_identity<signed char>" has already been defined
/ccsopen/proj/csc333/kokkos.install/include/Kokkos_ReductionIdentity.hpp(109):
error: class "Kokkos::reduction_identity<__nv_bool>" has already been defined
```
Drive-by change: split some longer lines for readability.
=> Wipe out previous kokkos and benchmark installs in gitlab-ci

src/kokkos_ext/ArborX_DetailsKokkosExtBitManipulation.hpp
Apparently, we only test for Kokkos >= 4.1.00 in our nightlies which don't build the tests but only the benchmarks.
=> Fix include files for ArborX_DetailsKokkosExtBitManipulation.hpp and Kokkos >= 4.1.00

src/details/ArborX_DetailsMortonCode.hpp, src/geometry/ArborX_HyperPoint.hpp, test/tstDetailsMortonCodes.cpp
https://github.com/dealii/dealii/pull/15538 wants to use `ArborX` for 1d, 2d and 3d data and we currently convert everything to 3d. In order to allow using the `HyperGeometry` types, 1d Morton codes are missing, though, and this pull request adds them.
=> Allow computing morton codes for 1-dim points

.jenkins/continuous.groovy
This is to avoid problems such as in #883 or https://github.com/dealii/dealii/issues/15749#issuecomment-1636919275.
We could choose a different build but probably can't use any CUDA build and the HIP one seemed to be as good as any other (without introducing an extra configuration).
=> Test with C++20 in HIP CI

.jenkins/continuous.groovy, docker/Dockerfile.sycl
There is not much of a point in testing with an intermediate version if we can use the release.
Drive-by: 
- We don't need to also install `icpc` but can restrict the Dockerfile to `icpx`. 
- We also need to update the base image, see https://github.com/kokkos/kokkos/pull/6288.
=> Test SYCL with Kokkos 4.1.00

src/ArborX_BruteForce.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsFDBSCAN.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsMutualReachabilityDistance.hpp, test/tstCompileOnlyCallbacks.cpp, test/tstCompileOnlyTypeRequirements.cpp, test/tstDetailsMutualReachabilityDistance.cpp, test/tstQueryTreeCallbacks.cpp
This PR does not touch the callbacks related to the `CrsGraphWrapper`.
=> Switch the signature for the pure callback

.jenkins/nightly.groovy
I'm not sure if the disabled tests and examples in the nightlies were intentional. If not, this would enable them for a more complete coverage. Examples were built separately post-install, but not as part of the build. I would be OK to not enable examples for in-build.
=> Enable tests and examples on the nightlies

src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, test/tstDetailsTreeConstruction.cpp
Leaf nodes will not always store bounding volume inside. We have to use the indexable for a degenerate tree.
=> Properly compute tree bounds with indexables

benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp, benchmarks/dbscan/ArborX_DBSCANVerification.hpp, src/ArborX_DBSCAN.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_MinimumSpanningTree.hpp
The right dimensionality of the box depends on the return type of the `IndexableGetter`.
=> Change default BoundingVolume for BasicBVH to the right dimensionality

.gitlab-ci.yml
Sometimes, they can't execute correctly due to the presence of the .nfs* (or similar) files from the filesystem. Which aborts the whole workflow. This will do the best effort to remove the install directory, but still continue if it only does partial cleanup.
=> Allow rm -rf commands fail on Gitlab CI

src/geometry/ArborX_HyperPoint.hpp, test/tstCompileOnlyAccessTraits.cpp
In response to https://github.com/arborx/ArborX/pull/916#issuecomment-1662433663 and https://github.com/arborx/ArborX/pull/916#discussion_r1282012041.
- ~~we ensure that the template type argument is a floating point type.~~
- the deduction guide now works for all dimensions, and uses `double` if any of the arguments is a `double` and `float` otherwise.
=> Improve deduction guide for ExperimentalHyperGeometry::Point

src/geometry/ArborX_HyperTriangle.hpp, src/geometry/ArborX_Ray.hpp, src/geometry/ArborX_Triangle.hpp, test/tstRay.cpp
Related to #542, #784, and #903.
This pull requests templates `ArborX::Experimental::Triangle` on the underlying points' dimension and floating point type. We discussed in the meeting that we don't care much about backward compatibility since the class is an Experimental namespace.
I chose to template separately on the dimension and floating point type instead of on the `Point` type for consistency with the classes in the `ExperimentalHyperGeometry` namespace.
~~Drive-by: We forgot to use the floating point type template argument in `ArborX::ExperimentalHyperGeometry::Sphere`'s GeometryTraits.~~
=> Template Triangle on dimension and floating point type 

.jenkins/nightly.groovy
Nightly tests fail because the CUDA build has enabled tests with boost 1.74. That was enabled in #913. My fault, I didn't understand @dalg24's [comment](https://github.com/arborx/ArborX/pull/913#discussion_r1270873170).
This patch disables tests, but keeps examples enabled. 
The alternative would be to install a newer boost version, either manually or using something an [external repo](https://launchpad.net/~mhier/+archive/ubuntu/libboost-latest). I chose simplicity as to not add a fragile point.
=> Disable tests in the nightly CUDA build

.jenkins/continuous.groovy
We are seeing
```
clang++: warning: linked binaries do not contain expected 'nvptx64-nvidia-cuda' target; found targets: 'nvptx64-nvidia-cuda-sm_70' [-Wsycl-target]
```
a bunch in the CI. Supposedly, this was fixed by https://github.com/intel/llvm/pull/7434. It shouldn't matter much anyway (and if so it would be more of a `Kokkos` issue than an `ArborX` issue) and there is no reason to fail the CI because of this warning.
=> Suppress -Wsycl-target warnings for SYCL CI

src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
Fixes #926. I didn't see much of a difference in performance but that also wasn't really expected at this point.
=> Use oneapi::dpl::sort_by_key if possible

benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsMortonCode.hpp, test/tstCompileOnlyTypeRequirements.cpp
#916 made me realize that we never tested whether we are able to actually run a hierarchy built using `double`. Turns out we didn't. This patch fixes it, and updates one of the benchmarks (brute vs bvh) to run both float and double.
Scope:
- Fixes few places in the hierarchy where we unconditionally used `Box<DIM>` and similar
- Updates a benchmark
=> Allow different floating point types in hierarchy

src/details/ArborX_DetailsDistributor.hpp
Compiling with cuda-12.2 gives errors like
```
cd /app/ArborX/build/test && /app/kokkos-cuda-12.2/bin/kokkos_launch_compiler /app/kokkos-cuda-12.2/bin/nvcc_wrapper /usr/bin/c++ /usr/bin/c++ -DARBORX_MPI_UNIT_TEST -DBOOST_TEST_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_NO_LIB -DKOKKOS_DEPENDENCE -I/app/ArborX/build/test -I/app/ArborX/src -I/app/ArborX/src/details -I/app/ArborX/src/geometry -I/app/ArborX/src/kokkos_ext -I/app/ArborX/build/include -isystem /app/kokkos-cuda-12.2/include -isystem /usr/local/cuda/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /opt/boost/include -O2 -g -DNDEBUG -extended-lambda -Wext-lambda-captures-this -arch=sm_80 -std=c++17 -MD -MT …
```
=> Fix compiling with cuda-12.2

examples/CMakeLists.txt, examples/triangle_intersection/CMakeLists.txt, examples/triangle_intersection/triangle_intersection.cpp
This should be useful for `XGC`. In particular, this pull request separates `TreeTraversal` construction and actually running the search allowing applications to use the `TreeTraversal` class in their own `Kokkos` kernels.
=> Add example for 2D triangle-point intersection 

.jenkins/nightly.groovy
We don't have an MPI-enabled nightly test. In addition, a recent issue #933 highlighted a need for a newer CUDA build.
I opted to not enable GPU-aware MPI. I'm not sure if the default installed openmpi from Ubuntu would have it anyway.
=> Add CUDA-12.2.0-MPI nightly build

.jenkins/continuous.groovy
ArborX's ccache is using too much memory and filling up the machines. This should fix the issue.
=> Decrease the amount of memory used ccache

examples/triangle_intersection/triangle_intersection.cpp
Fixes the warning seen in https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-937/1/clang/source.76f6aa80-42a7-46d1-839a-2a98ba42596e/#371. We didn't notice earlier since the `HIP` build in https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/ArborX/detail/PR-542/18/pipeline timed out.
=> Avoid warning in return argument of triangle_intersection example

src/details/ArborX_DetailsTreeConstruction.hpp, test/tstCompileOnlyTypeRequirements.cpp
This will use GeometryTraits machinery instead of relying on a specific type (Box) to provide += operator for all other geometries.
It is backwards compatible, as currently users only allowed to provide Point and Box, which are both ArborX types. So we control everything here.
The motivation here is to not provide `Box += KDOP` (as we already have an `expand` for it), as that is something one would have to do if constructing APIv2 hierarchy on KDOPs and calculating scene bounding box.
=> Use expand instead of += during scene calculation

src/ArborX_LinearBVH.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsHalfTraversal.hpp, src/details/ArborX_DetailsLegacy.hpp, src/details/ArborX_IndexableGetter.hpp, test/tstDetailsTreeConstruction.cpp
This is just moving stuff around, no new code is introduced. Want to make `ArborX_IndexableGetter.hpp` and `ArborX_Callbacks.hpp` free from all the `Legacy` stuff, and move it to one place.
=> Move APIv1 converters into a separate legacy header

src/geometry/ArborX_DetailsAlgorithms.hpp, src/geometry/ArborX_GeometryTraits.hpp, test/tstDetailsAlgorithms.cpp
This PR adds several routines and updates:
- `centroid(Triangle)`
- `expand(Box, Triangle)`
- `intersects(Point, Triangle)` (2D only)
- changes all `centroid` and `intersects` calls to `constexpr`
The first two are necessary to be able to construct a hierarchy based on triangles. The third one is useful for the 2D triangle intersection example and applications (like XGC/Tokamak). The last one is a drive-by change
=> Add several algorithm routines for triangles

test/utf_main.cpp
Passing an argument recognized by Kokkos to a test executable yields a segfault.
The issue is that Kokkos decrement the argument counter and shift the arguments but Boost.Test gets the original count and dereferences a null pointer.
=> Fix bug argument counter must be passed by reference

src/geometry/ArborX_DetailsAlgorithms.hpp
Also replace std::sqrt by Kokkos::sqrt to allow for half_t and bhalf_t calculations in the future.
=> Get rid of hardcoded float in the geometry algorithms

src/ArborX_LinearBVH.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsHappyTreeFriends.hpp, src/details/ArborX_SpaceFillingCurves.hpp
We have few places that use a combination of `decltype` and `declval` that could be simplified by using `invoke_result_t` (available starting c++17).
=> Switch to using invoke_result_t 

.github/workflows/windows.yml, .gitignore, src/interpolation/details/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp, test/ArborX_EnableViewComparison.hpp, test/CMakeLists.txt, test/tstInterpDetailsSVD.cpp, test/tstInterpDetailsSymmPInvSVD.cpp
In an attempt to break-up #946, this PR focuses only on the pseudo inverse used in the moving least squares algorithm. It includes the pseudo inverse itself in `src/interpolation` folder, tests and ~~an iterator for multi-dimensional views (for use in boost tests)~~ a macro to test equality on md views
=> Pseudo-inverse of symmetric matrices using SVD / Utility for moving least squares

benchmarks/brute_force_vs_bvh/brute_force_vs_bvh.cpp, benchmarks/dbscan/ArborX_DBSCANVerification.hpp, benchmarks/dbscan/data.hpp, benchmarks/execution_space_instances/execution_space_instances_driver.cpp, benchmarks/union_find/union_find.cpp, examples/brute_force/brute_force.cpp, examples/molecular_dynamics/example_molecular_dynamics.cpp, examples/simple_intersection/example_intersection.cpp, examples/triangle_intersection/triangle_intersection.cpp, examples/viz/tree_visualization.cpp
Nightlies are broken following the merge of kokkos/kokkos#6482
=> Include `<iostream>` when using it in examples and benchmaks

src/interpolation/details/ArborX_InterpDetailsCompactRadialBasisFunction.hpp, src/interpolation/details/ArborX_InterpDetailsPolynomialBasis.hpp, test/ArborX_EnableViewComparison.hpp, test/CMakeLists.txt, test/tstInterpDetailsCRBF.cpp, test/tstInterpDetailsPolyBasis.cpp
Follow-up of #946 and #950. This PR adds the set of radial basis functions that were present on DTK, a generic way of building a polynomial basis and tests for both of them.
- Adds `ArborX::Interpolation::CRBF`, a namespace containing the compact radial basis functions `Wendland`, `Wu` and `Buhmann`.
=> Compact radial basis functions and generic polynomial basis / Utility for moving least squares

benchmarks/bvh_driver/bvh_driver.cpp
Oversight in #956 
I just noticed the GCC nightly build was still broken.
Sorry about that.
=> Fixup one more missing `<iostream>` header include

benchmarks/dbscan/ArborX_DBSCANVerification.hpp, examples/callback/example_callback.cpp, examples/raytracing/example_raytracing.cpp, examples/triangle_intersection/triangle_intersection.cpp
The header file (`impl/Kokkos_Printf.hpp`) is not public so we are relying on `Kokkos_Core.hpp` for now.
Maybe, we can promote the header before the release, see https://github.com/kokkos/kokkos/pull/6506.
=> Use Kokkos::printf for Kokkos >= 4.2.00

benchmarks/dbscan/ArborX_DBSCANVerification.hpp, examples/raytracing/example_raytracing.cpp, examples/triangle_intersection/triangle_intersection.cpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsUtils.hpp
(from the [comment](https://github.com/arborx/ArborX/pull/946#discussion_r1362183134))
Kokkos developers suggest not to initialize the value one reduces into because it may give the wrong impression to users, that the reduced value will be contributed to an initial value or whatnot, when Kokkos will actually ignore that value and overwrite it with the result of the reduction.
=> Do not initialize the value we reduce to

src/details/ArborX_DetailsCartesianGrid.hpp, src/details/ArborX_DetailsContainers.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsHappyTreeFriends.hpp, src/details/ArborX_DetailsNode.hpp, src/details/ArborX_DetailsPriorityQueue.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/details/ArborX_DetailsTreeNodeLabeling.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/geometry/ArborX_DetailsAlgorithms.hpp, src/geometry/ArborX_Ray.hpp
=> Replace assert with KOKKOS_ASSERT in kernel code

src/details/ArborX_MinimumSpanningTree.hpp, test/tstDendrogram.cpp
Fix cases where a dendrogram could become non-binary due to same weight edges
=> Fix Boruvka dendrogram generation

benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp, benchmarks/dbscan/ArborX_DBSCANVerification.hpp, src/ArborX_BruteForce.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsLegacy.hpp, test/ArborXTest_LegacyTree.hpp, test/tstCompileOnlyCallbacks.cpp
Change the signature of the callback:
```diff
-callback(Predicate const &predicate, int primitive_index, OutputFunctor &functor);
+callback(Predicate const &predicate, Value const &value, OutputFunctor &functor);
```
=> APIv2: change signature of the 3-argument callback

test/CMakeLists.txt
We introduced the workaround in b415d366 (#286). At the time, we used CMake 3.12 or later, which had the mix. Since then, we upgraded minimum CMake version to 3.16, which automatically includes the neccessary CMake patch (see
https://gitlab.kitware.com/cmake/cmake/-/commit/24342d5ef772b9873c0f041fb422503acc06ff50, click "Tags containing commit"). So the workaround is no longer necessary.
=> Remove workaround for getting Boost version in CMake

benchmarks/dbscan/ArborX_DBSCANVerification.hpp, src/ArborX_BruteForce.hpp, src/ArborX_DBSCAN.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_AccessTraits.hpp, src/details/ArborX_DetailsFDBSCANDenseBox.hpp, src/details/ArborX_DetailsMutualReachabilityDistance.hpp, src/details/ArborX_MinimumSpanningTree.hpp, test/tstNeighborList.cpp
The goal is to avoid using `AccessTraits` internally in ArborX, only at the user interface functions. Motivated by #729, and in preparation for `RangeTraits` introduction.
=> Cut down on the number of AccessTraits

CHANGELOG.md
The changelog is really sparse because most of the work was internal refactoring associated with APIv2.
=> [ci skip] Update CHANGELOG for 1.5

CMakeLists.txt, examples/CMakeLists.txt
Still struggle to figure out whether it should be 1.6 or 2.0.
=> Update version to 1.6 dev

src/interpolation/details/ArborX_InterpDetailsPolynomialBasis.hpp
This should avoid some changes in https://github.com/arborx/ArborX/pull/946, like https://github.com/arborx/ArborX/pull/946/files#diff-a2fce1f8ea3d6b4f0053b59757e3a38d63072a53b10f24a2b731821423a95cb8R93. We already test
```
static_assert(GeometryTraits::is_point<Point>::value,
"point must be a point");
```
and we use traits without further checks in other places already.
=> Drop check_valid_geometry_traits test from evaluatePolynomialBasis

src/geometry/ArborX_DetailsAlgorithms.hpp
We avoid `sqrt`, `max`, and couple arithmetics.
=> Avoid some extra calculations in intersects(sphere, point)

examples/molecular_dynamics/example_molecular_dynamics.cpp
Related to the discussion in https://github.com/arborx/ArborX/pull/986#issuecomment-1866563100
Without going into a debate of what to do with our `KokkosExt::ArithmeticTraits`, we should not have it in our examples and use the experimental numeric traits from Kokkos directly.
=> Do not showcase `KokkosExt::ArithmeticTraits` in our examples

examples/molecular_dynamics/example_molecular_dynamics.cpp
Related to the discussion in https://github.com/arborx/ArborX/pull/986#issuecomment-1866563100
Printing versions is relevant in benchmarks, it does not really belong to our examples.
This will avoid the issue about `KokkosExt::version()` that is an implementation detail.
=> Do not bother with printing ArborX and Kokkos versions in the examples

.jenkins/continuous.groovy, benchmarks/dbscan/ArborX_DBSCANVerification.hpp, src/ArborX_BruteForce.hpp, src/ArborX_DBSCAN.hpp, src/ArborX_DistributedTree.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_AccessTraits.hpp, src/details/ArborX_DetailsBatchedQueries.hpp, src/details/ArborX_DetailsBruteForceImpl.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsPermutedData.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_MinimumSpanningTree.hpp
=> Cut down on the number of AccessTraits<Predicates, PredicatesTag>

src/details/ArborX_PairValueIndex.hpp
This was an oversight. Combining #978 and #969 resulted in a problem, while each one on their own was fine.
We don't test the merged commit, just the branch one.
We only use `AttachIndices` during the construction, not traversal. Thus, we can hardcode the `PrimitivesTag`.
=> Fix missing tag within AttachIndices

src/details/ArborX_Callbacks.hpp
Refactor/ modernize callback introspection facility.  My initial goal was to get rid of `Details::AccessTraitsHelper` but I decided to split that up.
Fix bug introduced the refactor in #939 that makes that we were not catching errors like https://github.com/arborx/ArborX/blob/1dc256dff44ae10847175258dc43c750d1142240/test/tstCompileOnlyCallbacks.cpp#L141-L142))
=> Modernize and fix callback detection

src/details/ArborX_AccessTraits.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsLegacy.hpp
Rational: we introduced `AccessValues` (still not liking that name) which adapts the user input and effectively we have duplicated facility.  The new intended way should be to assume an adapted user input that provides dependent types.  This PR purges the old facility.
=> Drop `Details::AccessTraitsHelper`

test/Search_UnitTestHelpers.hpp, test/tstDistributedTree.cpp
It is only used in the distributed testing, and does not test anything useful. It prevents the refactoring of the DistributedTree as it reaches inside the implementation which would vary between the old and new interface.
Should have been removed as part of #366.
=> Remove ARBORX_TEST_QUERY_TREE_WITH_DISTANCE

src/interpolation/details/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp, src/interpolation/details/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp
This PR modifies the SVD pseudo-inverse and the coefficients computation, its main goal was to reduce the amount of global memory used, use scratch memory and compound the kernels.
=> Optimization for moving least squares

docker/Dockerfile.sycl
This reverts commit c47f38f002cc9dfa08466acdd58bd2537bc99402.
SYCL has been broken since #973. This PR is to try to make the CI pass again. We either downgrade, or figure out what's happening.
=> Revert "Update Kokkos to 4.2 in the SYCL build"

src/details/ArborX_Callbacks.hpp
While compiling ArborX for cuda, I had this warning:
```
warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed
out(i);
^
detected during:
instantiation of "void ExcludeSelfCollision::operator()(const Predicate &, int, const OutputFunctor &) const [with Predicate=ArborX::PredicateWithAttachment<ArborX::Intersects<ArborX::Sphere>, int>, OutputFunctor=ArborX::Details::Sink<int>]" at line 3261 of /usr/include/c++/11/type_traits
```
This small change got rid of that. 
The `ExcludeSelfCollision` callback is defined as:
```
struct ExcludeSelfCollision
{
template <class Predicate, class OutputFunctor>
KOKKOS_FUNCTION void operator()(Predicate const &predicate, int i,
OutputFunctor const &out) const
{
int const j = ArborX::getData(predicate);
if (i != j) …
```
=> Add KOKKOS_FUNCTION macro to Details::Sink::operator()

.clang-tidy, benchmarks/CMakeLists.txt, src/interpolation/details/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp
I think after redoing CI, we are no longer able to see clang-tidy warnings (possibly, warnings at all). This PR fixes one of the recent ones that creeped in, together with a more outstanding one.
=> Fix clang-tidy

src/details/ArborX_DetailsLegacy.hpp, src/details/ArborX_PairValueIndex.hpp
- Do not ignore the second template arg of PairValueIndex in LegacyCallbackWrapper
- Match the default for `Index` in `attach_indices` to the default in `PairValueIndex`
=> Minor cleanup to PairValueIndex and attach_indices

src/details/ArborX_PairValueIndex.hpp
https://github.com/arborx/ArborX/pull/1015#discussion_r1442369381
=> Switch template arg order for attach_indices

src/ArborX_DistributedTree.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributedTreeNearest.hpp, src/details/ArborX_DetailsDistributedTreeSpatial.hpp
- Change top tree to new API
- Change `Distances` args in `reassesStrategy` and `deviseStrategy` to const
- Change order of the args in `reassesStrategy` and `deviseStrategy` to align with query
- Introduce `BoundingVolume` alias in `DistributedTree` 
- Rename generic `indices` to `nearest_ranks` and `intersected_ranks` in DistributedTree queries implementation
- Fix several labels (regions, views, kernels) to follow the standard format
=> Switch top tree in DistributedTree to new API and do some cleanup

src/details/ArborX_AccessTraits.hpp, src/interpolation/ArborX_InterpMovingLeastSquares.hpp
> Was referred to directly in MLS which hinders changing what really should be considered implementation details.
Sorry I don't know what was wrong with #1018 
I opened it as GH was having issues. I had uploaded a new version that never showed up and the CI would not trigger.
=> `AccessValues::_values` data member should be private

src/ArborX.hpp
Rational: backward compatibility
Andrey did too good of a job at cleaning up unnecessary header includes and this led to the current situation where `<ArborX_DetailsUtils.hpp>` is not included in the `<ArborX.hpp>` header when MPI is not enabled which broke Cabana.
=> Explicitly include `<ArborX_DetailsUtils.hpp>` from `<ArborX.hpp>`

src/details/ArborX_AccessTraits.hpp, src/details/ArborX_DetailsLegacy.hpp, src/details/ArborX_DetailsPermutedData.hpp
The recent refactors makes us generate symbol names that are getting really nasty.  This is an attempt to "collapse" nested template template classes when possible to clean things up.  My fancy debugger does not let me copy/paste symbol name and I am too lazy/tired to type it down before and after but I think you will get the picture.
This is meant as a basis for discussion.  I went for minimal changes, I am not suggesting that aliasing `AccessValues` to some implementation class is a good design.
I implemented the following contractions
`AccessValues<AccessValues<...>> -> AccessValues<...>`
`AccessValues<Kokkos::View<...>> -> Kokkos::View<...>`
`AccessValues<PermutedData<...>> -> PermutedData<...>`
`AccessValues<LegacyValues<...>> -> LegacyValues<...>`
=> An attempt to cleanup symbols for values and predicates

src/details/ArborX_NeighborList.hpp, test/tstNeighborList.cpp
- Make it work with any points
- Build the underlying BVH on points instead of boxes for performance
- Add (memory space, execution space) checks
=> Generalize GetNeighborList for points

examples/simple_intersection/example_intersection.cpp
Originally, I wanted to create this example using 2D geometry. But it is still inconvenient to write it using the new interface:
```c++
ArborX::BVH<MemorySpace, ArborX::PairValueIndex<Box>>
tree(space, ArborX::Experimental::attach_indices(boxes));
tree.query(space, queries, ArborX::LegacyDefaultCallback{}, indices, offsets);
```
We have **three** annoying things: `PairValueIndex`, `attach_indices`, `LegacyDefaultCallback`.
We need to decide what to do about it.
=> Simplify the simple intersection example

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, src/ArborX_BruteForce.hpp, src/ArborX_DistributedTree.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributedTreeNearest.hpp, src/details/ArborX_DetailsDistributedTreeSpatial.hpp, src/details/ArborX_DetailsDistributedTreeUtils.hpp, src/details/ArborX_DetailsLegacy.hpp
- Refactor by introducing `DistributedTreeBase`
- Update distributed benchmark to take advantage of the new interface
This should also satisfy the requirements for #907, though the interface may be a bit hard to use initially.
I opted to go for the base templated on the bottom tree because all other methods were too intrusive between spatial implementation and wrapping the post callback.
=> Refactor DistributedTree to support APIv2

.jenkins/continuous.groovy, docker/Dockerfile.hipcc, src/ArborX_BruteForce.hpp, src/ArborX_LinearBVH.hpp, test/tstInterpDetailsMLSCoefficients.cpp, test/tstInterpMovingLeastSquares.cpp
- I bumped the HIP version from 5.3 to 5.6. There was a strange permission issue with ROCm 5.3 I don't understand why we have this problem but a quick google search told me that ROCm 5.5 fixed the issue. I bumped to ROCm 5.6 because that's why we use for Kokkos.
- I added missing `KOKKOS_FUNCTION`
- We still have an issue because the new MLS tests do not pass (`fatal error: in "mls_coefficients_edge_cases<Kokkos__Device<Kokkos__HIP_ Kokkos__HIPSpace>>": std::runtime_error: Kokkos::Impl::ParallelFor/Reduce< HIP > could not find a valid team size.`). The issue seems similar to the problem we have in Kokkos with the memory requirement tests. Disabling these for now.
=> Fix label for AMD GPU in the CI

CMakeLists.txt
The min version requirement was introduced in ROCm 3.9 days. We now depend on Kokkos 4, which requires ROCm 5.2, which comes with rocThrust 2.15.
The presence of the version requirement also breaks compiling with ROCm 6, as rocThrust has `SameMajorVersion` CMake compatibility mode instead of `AnyNewerVersion`, and rocThrust coming with ROCm 6 has version 3.x.
Fix #1028.
=> Remove min version requirement for rocThrust

benchmarks/dbscan/ArborX_DBSCANVerification.hpp, benchmarks/point_clouds/point_clouds.hpp, src/ArborX_BruteForce.hpp, src/ArborX_DBSCAN.hpp, src/ArborX_DistributedTree.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_AccessTraits.hpp, src/details/ArborX_DetailsCartesianGrid.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsMortonCode.hpp, src/details/ArborX_IndexableGetter.hpp, src/details/ArborX_MinimumSpanningTree.hpp, src/details/ArborX_NeighborList.hpp, src/details/ArborX_SpaceFillingCurves.hpp, src/geometry/ArborX_DetailsAlgorithms.hpp, src/geometry/ArborX_GeometryTraits.hpp, src/geometry/ArborX_HyperBox.hpp, src/geometry/ArborX_Ray.hpp, src/interpolation/ArborX_InterpMovingLeastSquares.hpp, src/interpolation/details/ArborX_InterpDetailsCompactRadialBasisFunction.hpp, src/interpolation/details/ArborX_InterpDetailsPolynomialBasis.hpp
I know this patch is noisy. Still, I'd like to get it in.
- Provide `is_<geometry>_v` helpers to avoid `is_<geometry>::value_type`
- Provide `coordinate_type_t<geometry>` helpers to avoid `coordinate_type<geometry>::type`
- Provide `is_valid_geometry`
- Provide `GeometryTraits` for `Ray`
=> Update code to use tag_t, coordinate_t, is_<geometry>_v

benchmarks/bvh_driver/benchmark_registration.hpp, src/ArborX_BruteForce.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_AttachIndices.hpp, src/details/ArborX_PairValueIndex.hpp, test/CMakeLists.txt, test/tstAttachIndices.cpp, test/tstCompileOnlyAccessTraits.cpp, test/tstNeighborList.cpp
Right now, `attach_indices` only works for primitives. For predicates, there is no convenient way to attach indices to predicates. The `attach` only works on a single predicate and not limited to indices.
Attaching indices to primitives and predicates result in different types and access methods. Primitives result in `PairValueIndex<Value, Index>`, while predicates result in an unspecified type that the index can be accessed by `getData()`.
I'm not sure how how much of a problem returning different types is. The function serves the same role for both primitives and predicates: conveniently adjust passed in data in some easy way for the hierarchy. Both types should really be undefined. The difference is that in the first case the argument appears in the hierarchy template specialization. …
=> Make attach_indices work for both primitives and predicates

benchmarks/CMakeLists.txt
Based on work @cz4rs done for Kokkos.
=> Auto-fetch benchmark when not available

.jenkins/continuous.groovy, docker/Dockerfile.sycl
This patch tries to avoid the SYCL CI issues we are seeing when running setvars.sh by setting the necessary environment variables in Dockerfile already.
Taken from kokkos/kokkos#6824.
=> SYCL CI: avoid using setvars.sh

.jenkins/nightly.groovy
https://cloud.cees.ornl.gov/jenkins-ci/job/FIX_ARBORX_HIP_NIGHTLIES/1/pipeline-console/?selected-node=10
Add `/opt/rocm` to the search path when configuring Kokkos as well.
The `ROCM_PATH` does not seem to be needed with that change.
=> Fix HIP nightlies for Kokkos to find rocThrust

src/details/ArborX_IndexableGetter.hpp
Right now, `DefaultIndexableGetter` only passes through points and boxes, unnecessarily restricting things. One, for example, cannot do
`ArborX::BVH<MemorySpace, Triangle> bvh(space, Kokkos::View<Triangle*>);`.
This patch extends passed through geometries to all that are considered valid in `GeometryTraits`.
=> Update DefaultIndexableGetter to work with all valid geometries

.jenkins/continuous.groovy, .jenkins/nightly.groovy
The MI210 machines seem more stable than the MI100 ones. Let's just use them instead.
=> Switch CI from MI100 to MI210

benchmarks/execution_space_instances/execution_space_instances_driver.cpp, examples/access_traits/example_cuda_access_traits.cpp
Fix #1049. Should fix nightly failures.
=> Make sure that CUDA instances are destroyed prior to destroying streams

src/ArborX_BruteForce.hpp, src/details/ArborX_DetailsBruteForceImpl.hpp, src/details/ArborX_DetailsNearestBufferProvider.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, test/CMakeLists.txt, test/tstKokkosToolsAnnotations.cpp, test/tstKokkosToolsDistributedAnnotations.cpp
This is a straightforward not-optimized version of the nearest query for BruteForce. I think, k=1 case should be separated out in the future, as it can be performed in a tiling manner similar to the spatial search. The same, however, can't be said about k > 1 case.
Right now, a single thread is allocated per predicate, that goes through all indexables. This limitation is due to the fact that we don't have a multi-thread PriorityQueue.
I reenabled the nearest queries tests in the tests.
My overall motivation for implementing this is to try using BruteForce as the top tree in the DistributedTree.
=> Implement nearest query for BruteForce

src/ArborX_DBSCAN.hpp, src/details/ArborX_DetailsFDBSCAN.hpp, src/details/ArborX_DetailsHalfTraversal.hpp, src/details/ArborX_NeighborList.hpp, test/tstDetailsHalfTraversal.cpp
The main thing is to change half-traversal callback from `callback(int, int)` to `callback(value, value)`.
Note that this change is not backwards compatible. However, `HalfTraversal` is experimental, so it should be fine.
=> Switch HalfTraversal to APIv2

benchmarks/CMakeLists.txt, benchmarks/triangulated_surface_distance/CMakeLists.txt, benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp
This constructs a triangular tesselation of a sphere, then computes the distances from a randomly generated point cloud to the surface. User can specify the number of refinements of isocahedron and its radius, as well as the number of query points. It also optionally allows for saving the mesh in the legacy VTK format.
=> Add triangulated surface distance benchmark

src/details/ArborX_DetailsDistributedTreeNearest.hpp, src/details/ArborX_DetailsDistributedTreeSpatial.hpp, src/details/ArborX_DetailsDistributedTreeUtils.hpp, test/tstDetailsDistributedTreeImpl.cpp
- If we only have one view to sort, we can do it in a single sweep using sort_by_key instead of first computing permutation and then applying it.
- Allow changing keys and rename to `sortResultsByKey` to make this clearer
=> Improve distributed sorting of the results

.jenkins/nightly.groovy
Nightlies' HIP has been failing since #1048. 
The change in continuous has been fine. But it broke the nightlies.
The alternative would be to upgrade nightly to ROCm 5.6. I have no strong opinion. 
cc @Rombur
=> Revert MI100->MI210 for nightly testing

benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp, benchmarks/dbscan/ArborX_DBSCANVerification.hpp, examples/simple_intersection/example_intersection.cpp, src/ArborX_BruteForce.hpp, src/ArborX_LinearBVH.hpp, src/details/ArborX_PairValueIndex.hpp
Right now, it is inconvenient to get the old behavior. One has to write
```c++
ArborX::BVH<MemorySpace, ArborX::PairValueIndex<Box>>
tree(space, ArborX::Experimental::attach_indices(boxes));
tree.query(space, queries, ArborX::LegacyDefaultCallback{}, indices, offsets);
```
The presence of the `LegacyDefaultCallback` is really annoying.
This patch changes this. It automatically adds LegacyDefaultCallback
if the following 3 conditions are satisfied:
1. A user does not provide a callback
2. The index is constructed on PairValueIndex
2. The output value_type matches the index_type in the PairValueIndex.
=> Simplify using APIv1 through APIv2 interface

src/details/ArborX_DetailsFDBSCANDenseBox.hpp
When Kokkos is compiled with `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON`, examples/dbscan reports
```
1: Kokkos::RangePolicy bounds error:
The lower bound (1) is greater than the upper bound (0).
```
This is coming from this function, where RangePolicy starts at 1. This is a minor change to exit early. An additional benefit is not launching the kernel when n <= 1.
=> Exit early from unionFindWithingEachDistanceCell when n <= 1

src/ArborX_LinearBVH.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp, src/details/ArborX_DetailsTreeTraversal.hpp, src/details/ArborX_Predicates.hpp
The predicate tags really are implementation details and do not belong to the `Experimental::` namespace.
=> Move `OrderedSpatialPredicateTag` where it belongs that is namespace `Details::`

src/geometry/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp
Implements 3d box-triangle intersection based on the simplification in https://fileadmin.cs.lth.se/cs/Personal/Tomas_Akenine-Moller/code/tribox_tam.pdf to the Separating Axis Theorem.
=> Implement Box-Triangle intersection

src/details/ArborX_AccessTraits.hpp, src/details/ArborX_Callbacks.hpp, test/tstCompileOnlyAccessTraits.cpp
=> Remove deprecated `InlineCallbackTag` and `ArborX::Traits`

src/geometry/ArborX_GeometryTraits.hpp, src/geometry/ArborX_Tetrahedron.hpp, test/tstDetailsAlgorithms.cpp
For now, `intersects(point, tetrahedron)` is part of the tetrahedron file. Will be refactored in #1076.
=> Add Tetrahedron geometry

benchmarks/distributed_tree_driver/CMakeLists.txt, benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, benchmarks/utils/time_monitor.hpp
I'm writing a second benchmark (distributed nearest to wall) that would need this utility. So, moving it out of the current distributed benchmark. Code is unchanged.
Ideally, we would add tests at some point. Out of scope in this PR, though.
=> Move distributed TimeMonitor in a separate header

src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributedTreeNearest.hpp, src/details/ArborX_DetailsDistributedTreeSpatial.hpp, src/details/ArborX_DetailsDistributedTreeUtils.hpp
- Move common part from the spatial and nearest searches into `forwardQueriesAndCommunicateResults`
- Do not sort ranks for spatial searches and the first phase of the nearest search (it is unnecessary)
- Do not store and communicate values in the first phase of the nearest search; instead, only store the distances and communicate those
- Use nth_element algorithm instead of priority queue for determining the farthest distance in the nearest first phase; only use distances in the algorithm instead of pairs of values and distances
- Separated the code in the nearest `queryDispatchImpl` into `phaseI` and `phaseII` with interfaces making clear which data is passed where
- Some minor general improvements 
The overall goal of the PR is to prepare for reduce complexity. This should also help …
=> Refactor distributed query internals

src/details/ArborX_SpaceFillingCurves.hpp
This prevented computing Morton codes for user geometries even if they provided `returnCentroid`.
=> Allow user-provided returnCentroid

src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
This is important for types that are not default constructible.
Could theoretically do `KokkosExt::reallocWithoutInitializing(space, out, 0);`. Not sure what the difference is.
=> Do WithoutInitializing when resizing output view in CrsGraph

src/details/ArborX_DetailsBruteForceImpl.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/geometry/ArborX_Box.hpp, src/geometry/ArborX_DetailsAlgorithms.hpp, src/geometry/ArborX_HyperBox.hpp, test/tstIndexableGetter.cpp
Right now, we do a combination of `+=` and `expand` in our reduction. I would like to switch to only using `expand` in order to make the geometric algorithms a general as possible. `+=` relies on internal implementation, while `expand()` tells us exactly what operations a, say, `Box` geometry is required to provide.
The goal here is to move all stuff from inside the geometry classes (this includes KDOP and Ray, too) into generic algorithms.
- Deprecate `reduction_identity` in `ArborX::Box` and `ArborX::ExperimentalHyperGeometry::Box` (*not sure why we didn't have one in KDOP*)
- Deprecate `+=` in `ArborX::Box`
- Remove `+=` in `ArborX::ExperimentalHyperGeometry::Box`
- Switch scene calculation to using functors with `join` operation using `expand`
- Provide a generic implementation of …
=> Switch to using expand for scene reductions

src/ArborX_DistributedTree.hpp, src/details/ArborX_Callbacks.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributedTreeNearest.hpp, src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp, src/details/ArborX_DetailsDistributedTreeUtils.hpp, src/details/ArborX_DetailsLegacy.hpp, test/tstDistributedTree.cpp
[The 3-round rework of #737 will be pushed in that branch once this PR has been merged].
Works for both APIv1 and APIv2 (that was quite tricky).
Introduces two ways to do a nearest callback in the distributed setting:
- 2-round communication for a constrained callback
Constrained meaning that
- It is allowed to be called on not final matches
- For each match, it outputs exactly one result
Constrained callback is indicated with a new tag.
Current limitations:
- I have not thought yet about post-callbacks and whether they should be allowed
To be fair, even with the spatial callbacks I'm not sure what that means
=> Distributed nearest callback

src/details/ArborX_DetailsHappyTreeFriends.hpp
This is not necessary anymore. Tested on frontier with rocm 5.2 and rocm 5.4.3. I don't have the input data to run DBSCAN (I keep losing it), so @aprokop should probably check that it gets the same results.
The different path for HIP was first introduced in #575.
=> Remove unnecessary work-around for HIP

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp, test/tstBoostGeometryAdapters.cpp, test/tstDistributedTree.cpp, test/tstKDOP.cpp, test/tstMinimumSpanningTreeGoldenTest.cpp, test/tstQueryTreeCallbacks.cpp, test/tstQueryTreeComparisonWithBoost.cpp, test/tstQueryTreeDegenerate.cpp, test/tstQueryTreeManufacturedSolution.cpp, test/tstQueryTreeRay.cpp
In preparation for switching Point to hyper Point.
I aliased `using Point = ExperimentalHyperGeometry::Point<3, float>;` and fixed all the resulting errors. This PR, however, does not make the switch itself.
~If we used C++20, some of them could have been avoided. For example, `(a, b, c)` -> `{a, b, c}` switch and `emplace_back` would work as C++20 allows parenthesis aggregate initialization.~ *Update:* C++20 (p0960)[https://wg21.link/p0960] does **not** allow initialization of inner array with parenthesized list of values.
=> Use floats to construct Point in tests and benchmarks

.github/workflows/windows.yml
~Let's see if it fixes recent failures.~
Of course not. If only one looked at the logs:
```
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: D:\a\ArborX\ArborX\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.3976.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
```
The problem is microsoft/vcpkg#38974. I switched to requiring a specific hash for `microsoft/vcpkg` temporarily until the next release.
=> Update Windows Github action

.clang-format
The previous iteration would allow
```c++
int constexpr blah;
```
The new one would trigger on it.
I did not put 'friend' (should it be left-most?) and 'restrict' (we never use it).
=> Use custom QualifierOrder in clang-format

benchmarks/bvh_driver/benchmark_registration.hpp, benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp, benchmarks/utils/ArborXBenchmark_PointClouds.hpp
Generating large point clouds (like 100M) on host takes about half a minute (on Frontier), which makes it challenging to run multiple benchmarks. This PR does generation on the device. In addition, this PR fixes point generation for sphere and hollow sphere to produce uniform distributions and work better for high dimensions.
The generation is done in batched mode. I compared generating a certain number of random floats on A100 using different batches using the following driver:
[kokkos_vs_std_random.cpp](https://github.com/user-attachments/files/15537921/kokkos_vs_std_random.txt).
There's not much difference once one goes beyond batch 4:
```
--------------------------------------------------------------------------
Benchmark                                Time             CPU …
```
=> Generate point clouds on device

src/details/ArborX_DetailsUtils.hpp
This drops the number of host-device copies in the distributed nearest neighbors to 2. In a benchmark I'm running, 98% of the time is taken by copies. So, this speeds things up by 30%. Just the first patch of several to improve the performance.
=> Avoid double deep_copy in create_layout_right_mirror_view_and_copy for compatible layouts

src/details/ArborX_DetailsLegacy.hpp
This is a small change to avoid a compiler warning on both Intel and Nvidia compilers.  The warning is incorrect, but it is muddying up compile output and the dashboard results for the Sierra Toolkit.
The warning is that (sometimes) the compiler thinks:
```c++
double foo()
{
if constexpr (...)
{
return 42;
} else
{
return 0;
}
}  // warning here about lack of return statement in non-void function
```
is missing a return statement.
=> Work around spurious "missing return statement" warnings for NVCC and Intel compilers

src/details/ArborX_DetailsDistributor.hpp, test/tstDetailsDistributedTreeImpl.cpp
This information can be trivially obtained from offsets.
=> Do not store source/destination counts in Distributor

.github/workflows/windows.yml
[2024.06.15](https://github.com/microsoft/vcpkg/releases/tag/2024.06.15) has been released.
=> Remove specific hash requirement for microsoft/vcpkg

test/tstDBSCAN.cpp
Some rounding stuff on failed on Sunspot. This should be (slightly) more robust.
=> Fix DBSCAN test on Intel

test/Search_UnitTestHelpers.hpp
Motivation is prepare for testing the same execution space.
I was of two minds whether the execution space for creating queries should go first or second. Opted for the less code churn.
=> Fix execution spaces in the tests

src/ArborX_DistributedTree.hpp, src/details/ArborX_DetailsDistributedTreeImpl.hpp, src/details/ArborX_DetailsDistributedTreeSpatial.hpp, src/details/ArborX_DetailsDistributedTreeUtils.hpp, test/tstDistributedTreeSpatial.cpp
This adds a
```
template <typename ExecutionSpace, typename Predicates, typename Callback>
void query(ExecutionSpace const& space,
Predicates const& predicates,
Callback const& callback) const;
```
overload for `DistributedTree` (and `SpatialTag) with the callback being executed on the MPI process storing the primitives.
=> Add DistributedTree query only taking a callback

.jenkins/continuous.groovy, docker/Dockerfile.sycl
Alternative to #1118. Uses the same approach as in https://github.com/kokkos/kokkos/pull/7112 to avoid errors such as
```
--2024-06-28 16:01:41--  (try: 2)  https://registrationcenter-download.intel.com/akdlm/irc_nas/19133/l_oneDPL_p_2022.0.0.25335.sh
Connecting to registrationcenter-download.intel.com (registrationcenter-download.intel.com)|23.211.176.50|:443... 
connected.
HTTP request sent, awaiting response... 
No data received.
```
when building the SYCL image used in the CI.
=> SYCL CI: Manually build oneDPL

CMakeLists.txt
=> Set policy CMP0167 to use FindBoost module

.git-blame-ignore-revs
GitHub provides a [newish](https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/) (March 2022) [option](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) to ignore revisions in the blame view. I added 4 commits to the specified files to ignore 4 formatting patches we had:
- 18e8e71c8fbbb9e46bbc4e0fcad9986778fe9793 [clang-format 14.0]
- c301dd34ea30800b051f72b78cd93d2d33eae4b2 [clang-format 7.0]
- 08d6ebb08782ff40559230ef34a4008f15453f71 [clang-format 6.0]
- 85705177e98282db10b10026e8ae3cd0bc1fedad [clang-format 5.0]
=> [ci skip] Add .git-blame-ignore-revs to skip clang-format changes for blame

src/details/ArborX_DetailsVector.hpp, src/geometry/ArborX_Ray.hpp, test/tstDetailsVector.cpp
- Allow `Vector::dot` to be in a precision different from its type
- Allow `Vector::norm` to be in a precision different from its type
- Add `Vector::normalize()`
- Switch `Ray` to using new precision Vector functions
=> Update Vector to add computation precision and normalize()

src/geometry/ArborX_GeometryTraits.hpp, test/tstCompileOnlyGeometry.cpp
Currently, code using things like `dimension_v<const Point>` does not work. This addresses the issue by passing provided template parameter `Geometry` through `std::remove_cv`.
Once we start requiring C++20, should probably switch to `std::remove_cvref`.
=> Pass GeometryTraits template args through remove_cv

benchmarks/triangulated_surface_distance/generator.hpp
=> Fix triangulated_surface_distance benchmark when using Kokkos 4.4

src/geometry/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp
Missed in #1079.
Tested that constructing a hierarchy on the tets compiles:
```cpp
#include <ArborX.hpp>
#include <ArborX_Tetrahedron.hpp>
#include <Kokkos_Core.hpp>
int main(int argc, char *argv[])
{
Kokkos::ScopeGuard guard(argc, argv);
using Tetrahedron = ArborX::ExperimentalHyperGeometry::Tetrahedron<>;
using Point = ArborX::ExperimentalHyperGeometry::Point<3>;
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using MemorySpace = typename ExecutionSpace::memory_space;
ExecutionSpace exec;
Kokkos::View<Tetrahedron *> tets("Example::tets", 5);
ArborX::BVH<MemorySpace, ArborX::PairValueIndex<Tetrahedron>> bvh(
exec, ArborX::Experimental::attach_indices(tets));
Kokkos::View<decltype(ArborX::intersects(Point{})) *, MemorySpace> queries(
"Example::queries", 3);
Kokkos::View<int *> …
```
=> Add centroid for Tetrahedron

CMakeLists.txt, examples/CMakeLists.txt
Figure it would be safer to allow us to start breaking backwards compatibility.
=> Switch ArborX version to 2.0

src/details/ArborX_DetailsBruteForceImpl.hpp, src/details/ArborX_DetailsTreeConstruction.hpp, src/geometry/ArborX_Box.hpp, src/geometry/ArborX_DetailsAlgorithms.hpp, test/CMakeLists.txt, test/tstDetailsGeometryReducer.cpp, test/tstIndexableGetter.cpp
Redoing #1082. Removing Box's `+=` operator exposed that it did not work. 
It should not be possible to reduce all geometries, not just `Box`.
=> Add GeometryReducer and remove Box::operator+=

src/ArborX_DistributedTree.hpp, src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp, src/details/ArborX_DetailsDistributedTreeSpatial.hpp, test/Search_UnitTestHelpers.hpp, test/tstDistributedTreeNearest.cpp, test/tstDistributedTreeSpatial.cpp, test/tstKokkosToolsDistributedAnnotations.cpp
I am punting on testing in this PR. I made all previous testing work by constructing a DistributedTree based on `PairIndexRank` with a custom indexable getter. This way, I didn't need to change any of the distributed queries and results comparisons here.
A better testing framework for APIv2 will be developed after I get rid of APIv1.
=> Get rid of APIv1 in DistributedTree

src/ArborX_DBSCAN.hpp, src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp, src/details/ArborX_NeighborList.hpp, src/details/ArborX_PredicateHelpers.hpp, src/geometry/ArborX_DetailsAlgorithms.hpp, test/tstDetailsAlgorithms.cpp
Spurred by the discussion in #1146.
Add a convert function. Currently only for points.
The interface differs from [Boost's convert](https://live.boost.org/doc/libs/1_86_0/libs/geometry/doc/html/geometry/reference/algorithms/convert.html), as to streamline its usage in our code (right now, we only use its result to immediately construct spheres). May change in the future should we want it.
=> Add convert() for geometries

benchmarks/execution_space_instances/execution_space_instances_driver.cpp, benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp, examples/access_traits/example_cuda_access_traits.cpp, examples/access_traits/example_host_access_traits.cpp, examples/brute_force/example_brute_force.cpp, examples/callback/example_callback.cpp, examples/molecular_dynamics/example_molecular_dynamics.cpp, examples/raytracing/example_raytracing.cpp, examples/simple_intersection/example_intersection.cpp, examples/triangle_intersection/triangle_intersection.cpp, examples/viz/tree_visualization.cpp, src/geometry/ArborX_DetailsAlgorithms.hpp
This converts examples and all but one benchmarks to use APIv2. Without CTAD for now.
I also replaced `BVH` with `BoundingVolumeHierarchy` in preparation for later CTAD introduction.
Skipped `benchmarks/bvh_driver` because it's more involved. Will do in a separate PR.
Right now, it looks a bit ugly. I'm ignoring that, as the primary goal right now is to get rid of APIv1. Everything would require cleaning afterwards.
=> Switch examples and most benchmarks to APIv2

.jenkins/continuous.groovy, CMakeLists.txt, src/ArborX_DBSCAN.hpp, test/ArborXTest_LegacyTree.hpp
I propose we increase our requirement to 11.5 (released Oct 2021) right now. It is the minimum available version available on the platforms we care about (see [comment](https://github.com/arborx/ArborX/issues/974#issuecomment-2377210975)).
While I understand @dalg24 wants to go all the way to C++20 requirements (which would mean NVCC 12.0, released Dec 2022), I'm hesitant to do this right now. If we do decide to require C++20 for the release, we would do it then. Right now, this is blocking some of the work. 
I'm not saying that this is the minimum requirement we will do for ArborX 2.0 release. This is just an incremental update within the release cycle.
This PR:
- Switches CUDA-11.1.1 build to 11.7.1
- Removes pre 11.5 workarounds
This would unlock more code cleanup in #1141  and #1158, …
=> Increase minimum NVCC version requirement

src/details/ArborX_DetailsHappyTreeFriends.hpp, test/tstIndexableGetter.cpp
First push is the test to make sure CI gets the warning.
Second push is the fix.
=> Fix return type of getIndexable in HappyTreeFriends

examples/callback/example_callback.cpp, src/geometry/ArborX_Box.hpp, src/geometry/ArborX_Point.hpp, src/geometry/ArborX_Sphere.hpp, test/tstCompileOnlyGeometry.cpp, test/tstIndexableGetter.cpp, test/tstQueryTreeCallbackQueryPerThread.cpp, test/tstQueryTreeComparisonWithBoost.cpp, test/tstRay.cpp
Allow CTAD only for floating point types without any promotion.
=> Change Point, Box, Sphere CTAD

test/CMakeLists.txt
`dynamic_linking` brings `BOOST_ALL_DYN_LINK` in [3.16](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.16.0/Modules/FindBoost.cmake?ref_type=tags#L1461-1467). It's been there since 3.15.
Could have been done in #486.
=> Get rid of BOOST_TEST_DYN_LINK

src/kokkos_ext/ArborX_KokkosExtKernelStdAlgorithms.hpp, test/CMakeLists.txt, test/tstDetailsKokkosExtKernelStdAlgorithms.cpp
- Add `KokkosExt::upper_bound` kernel and tests
- Move KokkosExt tests out of `ArborX_Test_DetailsUtils`
=> Add upper_bound kernel

.jenkins/nightly.groovy
I've noticed that we have random failure of the nightly for gcc. It looks like a RAM issue, so I have decrease the number of processors used during compilation from 8 to 7. I have also update gcc from 13.1 to 14.2 because when we added the gcc 13.1 build, the goal was to test the latest gcc.  gcc 14 has partial support for C++26. So we could change the standard to C++26.
=> Update nightly CI gcc build

src/distributed/detail/ArborX_Distributor.hpp
Permutation was never used in the function.
=> Removed unused argument in determineBufferLayout

.github/workflows/windows.yml, CMakeLists.txt, docker/Dockerfile, examples/CMakeLists.txt
We are not backwards compatible for version 2.0. Allowing users' 1.x code to build against 2.0 is almost 100% would lead to build failures. Would rather prevent that during configuration.
Switching to `SameMajorVersion` would likely be temporary, for a few 2.x releases, after which we would switch back.
An alternative to switching to `SameMajorVersion` would be to update CMake requirements to at least 3.19 (release 11/18/2020, so about a year older than CMake we are using right now) and do
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -136,7 +136,7 @@ configure_package_config_file(cmake/ArborXConfig.cmake.in
)
write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/ArborXConfigVersion.cmake
VERSION ${ARBORX_VERSION_STRING}
-  COMPATIBILITY AnyNewerVersion
+  COMPATIBILITY …
```
=> CMake `AnyNewerVersion` -> `SameMajorVersion`

test/tstDBSCAN.cpp
This fixes the RelWithDebInfo test on PowerPC architecture.
I don't think we should be in business trying to reproduce exact arithmetic round off errors in the tests.
Hopefully, will pacify #1196.
=> Slightly increase radius in DBSCAN test

docker/Dockerfile, docker/Dockerfile.hipcc, docker/Dockerfile.sycl
Related to boostorg/boost#924
The agreement of Boost with JFrog came to an end in December 2024.
=> Change BOOST_URL to archives.boost.io

src/spatial/detail/ArborX_BruteForceImpl.hpp, src/spatial/detail/ArborX_NearestBufferProvider.hpp, src/spatial/detail/ArborX_TreeTraversal.hpp
I'm not sure whether to classify it as a bug or not. Essentially, we've been using reduced precision inside nearest query when running with `double`. All distances were calculated and converted to floats. It could lead to wrong results when two different doubles are converted to the same float
Need to figure out how to test it.
=> Fix hardcoded floats in TreeTraversal

benchmarks/dbscan/ArborX_DBSCANVerification.hpp
Default it to false so that we don't have any output in the tests by default.
=> Add verbose parameter to verifyDBSCAN

benchmarks/dbscan/ArborX_DBSCANVerification.hpp, src/cluster/ArborX_DBSCAN.hpp, src/cluster/detail/ArborX_CartesianGrid.hpp, src/cluster/detail/ArborX_FDBSCANDenseBox.hpp, test/tstDBSCAN.cpp
- Change internals of DBSCAN to be precision-agnostic
- Change DBSCAN test to run both float and double
=> Allow running DBSCAN in different precisions

src/interpolation/detail/ArborX_InterpDetailsPolynomialBasis.hpp, test/tstCompileOnlyAccessTraits.cpp, test/tstDendrogram.cpp, test/tstKokkosToolsExecutionSpaceInstances.cpp, test/tstQueryTreeCallbacks.cpp
Partially address #272 only for nvcc 11.5+. Addressing pre-11.3 requires a lot more work, and not sure it's worth it unless people complain. The plan it to switch to nvcc 11.5 or later once SummitPlus goes away.
=> Fix some nvcc warnings

src/geometry/ArborX_Segment.hpp, src/geometry/algorithms/ArborX_Centroid.hpp, src/geometry/algorithms/ArborX_Distance.hpp, src/geometry/algorithms/ArborX_Expand.hpp, src/geometry/algorithms/ArborX_Intersects.hpp, test/tstDetailsAlgorithms.cpp
- Rename `segment.{_start,_end}` to `segment.{a,b}`
- Add 2D segment-segment intersection
=> Add segment-segment intersection (2D only)

.jenkins/nightly.groovy
The nightly randomly fails on GCC 14. Decreasing the number of processors to see if that fixes the issue.
=> Decrease number of procs used to build ArborX in the nightly

benchmarks/cluster/ArborX_DBSCANVerification.hpp
- Refactor existing DBSCAN verification to allow it to work with both local and distributed cases
- Add (partial) distributed DBSCAN verification
The missing part is making sure cluster IDs are unique. For local, it uses DFS. Don't know how to implement it in distributed.
=> Add distributed DBSCAN verification

src/geometry/ArborX_Ellipsoid.hpp, src/geometry/ArborX_GeometryTraits.hpp, src/geometry/algorithms/ArborX_Centroid.hpp, src/geometry/algorithms/ArborX_Intersects.hpp, test/tstDetailsAlgorithms.cpp
- Add `Exprimental::Ellipsoid`
- Provide intersections with point, segment and box (2D only)
=> Add ellipsoid geometry

src/kokkos_ext/ArborX_KokkosExtKernelStdAlgorithms.hpp, test/tstDetailsKokkosExtKernelStdAlgorithms.cpp
Need to do binary_search on device within a Kokkos lambda. Could have used upper_bound, but it is slightly less clear.
=> Add lower_bound kernel

src/geometry/ArborX_Ray.hpp
Instead of dividing by zero, we set the value to -infinity or +infinity. For the case of `0/0`, we do not update `tdmin` and `tdmax`. This is what the current algorithm expects.
Related to https://github.com/arborx/ArborX/issues/1225.
=> Do not divide by zero when computing the ray-bounding box intersection

benchmarks/cluster/ArborX_DBSCANVerification.hpp, benchmarks/cluster/CMakeLists.txt, benchmarks/cluster/distributed_data.hpp, benchmarks/cluster/distributed_dbscan.cpp, benchmarks/cluster/parameters.hpp, src/cluster/ArborX_DistributedDBSCAN.hpp, src/cluster/detail/ArborX_DistributedDBSCANHelpers.hpp, src/distributed/detail/ArborX_DistributedTreeUtils.hpp
So far, only `minPts = 2` (FOF). Full-featured DBSCAN will be done in April. Performance optimizations will continue throughout the next few months.
Need it in `master` right now, so ignoring the testing requirement. 
Ran on Frontier and Aurora.
Frontier (GPU-aware MPI) on 64 ranks (8 nodes) with ~700M per rank (44B total):
```
ArborX version    : 1.7.99
ArborX hash       : e0dab986
Kokkos version    : 4.5.1
#MPI ranks        : 64
eps               : 1.000000
minpts            : 2
implementation    : fdbscan
n                 : 700,000,000
n_seq             : 100
spacing           : 2
verify            : false
verbose           : true
n (global)        : 44,663,302,592
#global merge pairs: 14715
total time          :      5.274
```
=> First non-naive version of distributed DBSCAN

src/spatial/detail/ArborX_PredicateHelpers.hpp, test/CMakeLists.txt, test/tstPredicateHelpers.cpp
Current implementation does not work because we don't call `AccessValues` constructor explicitly on the passed in data. This PR changes that, allowing to call `make_intersects` and friends on the data that is only provided through `AccessTraits`. Prior to this, `make_intersects` only worked with Kokkos views.
Fix #1231
=> Allow make_{intersects,nearest} work with `AccessTraits` data

.github/workflows/windows.yml, .jenkins/continuous.groovy, CMakeLists.txt, benchmarks/triangulated_surface_distance/generator.hpp, benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp, docker/Dockerfile, docker/Dockerfile.hipcc, docker/Dockerfile.sycl, src/cluster/detail/ArborX_CartesianGrid.hpp, src/distributed/ArborX_DistributedTree.hpp, src/geometry/ArborX_Box.hpp, src/geometry/ArborX_Ellipsoid.hpp, src/geometry/ArborX_Point.hpp, src/geometry/ArborX_Segment.hpp, src/geometry/ArborX_Sphere.hpp, src/geometry/ArborX_Triangle.hpp, src/interpolation/detail/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp, src/spatial/ArborX_BruteForce.hpp, src/spatial/ArborX_LinearBVH.hpp, src/spatial/detail/ArborX_ExpandHalfToFull.hpp, src/spatial/detail/ArborX_IndexableGetter.hpp, src/spatial/detail/ArborX_NeighborList.hpp, test/tstDetailsSVD.cpp
Note: Trilinos 16.1 contains Kokkos 4.5.1. So this update will still allow ArborX work with the latest Trilinos.
=> Require Kokkos 4.5

.clang-tidy, .jenkins/continuous.groovy, .jenkins/nightly.groovy, CMakeLists.txt, docker/Dockerfile, docker/Dockerfile.hipcc, docker/Dockerfile.nvcc, docker/Dockerfile.sycl, docker/README.md, src/spatial/detail/ArborX_IndexableGetter.hpp
TODO:
- `Clang+CUDA` build
Need to figure it out. Clang 14 seems to support up to cuda 11.5, and there are weird compilation failures with 12, it seems.
llvm/llvm-project#61340
It was only fixed in Clang 16
Updated to run Clang 18 with CUDA 12.5. `triangulated_surface` benchmark runs into `ptxas` error.
=> Require C++20

src/spatial/detail/ArborX_IndexableGetter.hpp, src/spatial/detail/ArborX_PairValueIndex.hpp, test/tstCompileOnlyTypeRequirements.cpp
In the current iteration, if a user has a custom geometry type that they try to build hierarchy on, it has to be tagged with one of the ArborX tags, which would call ArborX routines. This patch relaxes this requirement. Now, a user only needs to specify dimension and coordinate type.
I added a compile-only test that shows the requirements.
=> Remove requirement on knowing geometry types in IndexableGetter

src/ArborX.hpp
This is mostly to start a discussion about what headers should a user get when including `ArborX.hpp`. 
As I see it, there are two options:
1. A user gets no geometries at all through `ArborX.hpp` (other than included through indexes), and has to include each individual geometry they want to use
2. A user gets all the geometries
I see an issue with the first approach as a user will be transitively dependent on the geometries. If we change anything internally about inclusions, that will break user's code through no fault of their own. On the other hand, including all geometries is including a lot of code.
I'd like feedback on this.
=> Clean up ArborX.hpp

src/spatial/detail/ArborX_BruteForceImpl.hpp
We unintentionally always operated in low precision.
=> Remove hardcoded float from BruteForce nearest query

test/tstQueryTreeManufacturedSolution.cpp
=> Disable manufactured solution tree query test for SYCL with KDOP<14>

test/tstDendrogram.cpp
Dendrogram test can fail when the generated data produces an MST with equal edges. I was able to make the test fail using OpenMP on my Mac running the clustering test fewer than 10 times (using all threads; does not fail with OMP_NUM_THREADS=4).
One of the issues is that we draw the numbers from [0,1]^3 box, which may result in dropping the number of significant digits during distance calculation. As a workaround, I changed the box to [0, 100^3].
I can no longer reproduce the failure locally running it 1,000 times.
The alternative solution would be to use `double`. But at the moment, MST does not support any precision besides `float`.
This issue may fix #1113. It also spotted in #1196 ([this](https://github.com/arborx/ArborX/issues/1196#issuecomment-2524215592) comment).
=> Fortify dendrogram test

test/tstQueryTreeManufacturedSolution.cpp
Failed in #1250 (see [here](https://cloud1.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-1250/1/)).
=> Disable KDOP<18> manufactured query test for SYCL

src/spatial/detail/ArborX_PredicateHelpers.hpp, test/tstPredicateHelpers.cpp
Predicate helpers were using `UserPrimitives::memory_space` inside `AccessTraits` specializations instead of getting it through corresponding traits. This meant that even if the corresponding `AccessTraits` was written correctly, it did not work.
=> Fix a bug where predicate helper functions needed memory_space type in the type

src/geometry/algorithms/ArborX_BarycentricCoordinates.hpp, test/ArborX_EnableArrayComparison.hpp, test/CMakeLists.txt, test/tstGeometryBarycentricCoordinates.cpp
Add barycentric coordinates calculations for triangle and tetrahedron.
Adding to ArborX because it is useful for many other applications (e.g., interpolation).
=> Add barycentric coordinates algorithm (triangle and tetrahedron only)

test/tstQueryTreeComparisonWithBoost.cpp
Failed in #1260 ([failure](https://cloud1.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-1260/4/testReport/junit/projectroot/test/Build___SYCL___ArborX_Test_QueryTree/)).
=> Disable SYCL KDOP<14> for query comparison with Boost

src/cluster/detail/ArborX_DistributedDBSCANHelpers.hpp, src/spatial/detail/ArborX_IndexableGetter.hpp
Compilers reporting 17.0.0 are actually based on different sources trees. Some of them fail, some succeed. I think it's safe to only check for < 17.0.1 ([godbolt](https://godbolt.org/z/nEdjb5rP4)).
| Compiler | Status | Reported clang version
| --- | --- | ---
| icx 2023.2.1 | ❌  | 17.0.0 (icx 2023.2.0.20230721)
| icx 2024.0.0 | ✔️ | 17.0.0 (icx 2024.0.0.20231017)
| rocm 5.7.0 | ❌ | 17.0.0 (https://gihub.com/RadeonOpenCompute/llvm-project d1e13c532a947d0cbfc94759c00dcf152294aa13 | Failure
| rocm 6.0.2 | ❌ | 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project.git af27734ed982b52a9f1be0f035ac91726fc697e4 | Failure
| rocm 6.1.2 | ✔️ | 17.0.0 (https://github.com/ROCm/llvm-project.git 669db884972e769450470020c06a6f132a8a065b) | Success
| clang 16.0.0 | ❌  |
| clang 17.0.1 | ✔️ |
| Apple …
=> Update minimum clang version for aggregate initialization guide
