docker/Dockerfile
examples/bvh_driver/bvh_driver.cpp
examples/distributed_tree_driver/distributed_tree_driver.cpp
examples/viz/tree_visualization.cpp
src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
src/details/ArborX_DetailsSortUtils.hpp
src/details/ArborX_DetailsUtils.hpp
test/Search_UnitTestHelpers.hpp
test/tstDetailsBatchedQueries.cpp
test/tstDetailsDistributedSearchTreeImpl.cpp
test/tstDetailsUtils.cpp
test/tstDistributedSearchTree.cpp
test/tstLinearBVH.cpp

Fixes #28, fixes #34. Locally, all tests pass now. Needs some cleanup, though.

Disable deprecated code

---

src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp

Original discussion in ornl-cees/datatransferkit#534.

Add Kokkos profiling regions

---

examples/distributed_tree_driver/distributed_tree_driver.cpp

Properly set error code when failed in distributed example

---

test/Search_UnitTestHelpers.hpp

Admittedly not the necessarily the best place to put the code that print the tuple...

Enable comparison of tuples in unit tests

---

src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp

No real performance impact but the right thing to do

Take bvh by ref in query dispatch functions

---

cmake/SetupVersion.cmake

This adds  `--` in  front of the message

Add missing STATUS keyword in message

---

.jenkins

Amendment to #99 
I had assumed you grepped for `ArborX_ENABLE`...

Fixup for builds on Jenkins CI ArborX_ENABLE -> ARBORX_ENABLE

---

src/details/ArborX_DetailsAlgorithms.hpp
src/details/ArborX_DetailsKokkosExt.hpp
test/tstDetailsAlgorithms.cpp

https://github.com/arborx/ArborX/pull/97#issuecomment-532223529

Rollback more constexpr changes (isValid because of std::isfinite)

---

src/details/ArborX_DetailsAlgorithms.hpp
test/tstDetailsAlgorithms.cpp

I think this would be useful to have if a user wants to find boxes containing a point. While user could write this on his own, I think this is a common enough case for us to provide it.

Add intersects(Point, Box)

---

benchmarks/bvh_driver/bvh_driver.cpp
benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
examples/viz/tree_visualization.cpp
src/details/ArborX_DetailsBatchedQueries.hpp
src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
src/details/ArborX_DetailsSortUtils.hpp
src/details/ArborX_DetailsTreeConstruction.hpp
src/details/ArborX_DetailsUtils.hpp
test/tstDetailsTreeConstruction.cpp
test/tstDistributedSearchTree.cpp
test/tstLinearBVH.cpp

Remove all fences

---

src/details/ArborX_DetailsNode.hpp

Fixup after someone merged #153 without waiting for the CI
@aprokop One more commit!

Forgot <cassert> header

---

.jenkins

Related to https://github.com/arborx/ArborX/pull/163#issuecomment-546331977

Add timeout to CI step that runs the unit tests

---

src/details/ArborX_DetailsSortUtils.hpp

Suppress Thrust warnings

---

.jenkins

I am happy to discuss if we want to test for this option and if we want to have another configuration or modify an existing one as I do here.

Test CUDA-aware MPI in CI

---

.jenkins
docker/Dockerfile.pgi

Add PGI in .jenkins

---

.jenkins
src/details/ArborX_DetailsTreeVisualization.hpp

Fix #180 
TODO: Decide how to report warnings.

Enable compiler warnings in the CI

---

src/details/ArborX_DetailsDistributor.hpp

In combination with the `CUDA-aware` MPI pull request (#162), we should also be able to avoid copying `permutation_indices` to the CPU.

Parallelize sortAndDetermineBufferLayout

---

.jenkins

Let's try to figure out why this was giving unexpected failures/warnings.

Reenable quality gates

---

.jenkins

Update PGI build to display all warnings and test installation

---

.jenkins

Enable skipping the build on Jenkins

---

src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp

Buffer optimization fix for empty results

---

docs/bounding_volume_hierarchy.md
docs/predicates.md
docs/traits.md

BVH<{DeviceType -> MemorySpace}>
BVH<MemorySpace>::BVH(ExecutionSpace const &, ...)
BVH<MemorySpace>::query(ExecutionSpace const &, ...)

Update documentation to reflect recent changes in bvh

---

docs/bounding_volume_hierarchy.md
docs/traits.md

Fix reference in documentation

---

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp

https://github.com/arborx/ArborX/pull/256#pullrequestreview-387411205

Remove a few unnecessary view initialization in distributed search tree internals

---

docs/predicates.md

Somehow wasn't able to select @sslattery as reviewer
Just answered that question and realized it was not documented

Fixup document nearest(..., k=1) default argument

---

scripts/check_format_cpp.sh

- Provide an option to exclude files from consideration

Update check_format_cpp.sh script

---

src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp

Reported by @sslattery 
Problem was introduced in #271

Fix ambiguity in queryDispatch() overload resolution

---

test/Search_UnitTestHelpers.hpp
test/boost_ext/CompressedStorageComparison.hpp
test/tstLinearBVH.cpp

Improve error logs in linear bvh unit tests

---

src/details/ArborX_DetailsKokkosExt.hpp

https://github.com/arborx/ArborX/issues/321#issuecomment-634606433

Remove C++11 workaround definition of std::enable_if_t

---

.gitlab-ci.yml
benchmarks/bvh_driver/bvh_driver.cpp

Remove no header

---

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
src/details/ArborX_DetailsDistributor.hpp

For me, this fixes all the remaining problems with https://github.com/ORNL-CEES/DataTransferKit/pull/570.

Fix DistributedSearchTreeImpl::sendAcrossNetwork for DTK

---

src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
src/details/ArborX_DetailsDistributor.hpp
src/details/ArborX_DetailsUtils.hpp
test/tstDistributedSearchTree.cpp

This should fix the failing tests in https://github.com/ORNL-CEES/DataTransferKit/pull/574 while not impacting performance for the one-dimensional case.

Fix sendAcrossNetwork for multi-dimensional Views

---

benchmarks/distributed_tree_driver/distributed_tree_driver.cpp

Fix scaling issues in the distributed driver for 1D and 2D

---

.jenkins

Run Style check before Builds

---

examples/halo_finder/ArborX_HaloFinder.hpp
src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
src/details/ArborX_DetailsBufferOptimization.hpp
test/tstKokkosToolsAnnotations.cpp

Updated region labels according to #362 
Fixed https://github.com/arborx/ArborX/pull/388/files#r494254270
Also went ahead and updated a few kernel and view labels for consistency.

Update style of region labels and fixups

---

src/details/ArborX_DetailsTreeTraversal.hpp
test/tstKokkosToolsAnnotations.cpp
test/tstKokkosToolsDistributedAnnotations.cpp

Finish label renaming in TreeTraversal

---

.jenkins
docker/Dockerfile.hipcc

Locally this helped (in combination with `NDEBUG`) to fix the failing HIP test.

Update HIP CI to version 3.8

---

src/details/ArborX_DetailsTreeTraversal.hpp

The only goal of this PR is to make the style of the class members consistent. It is not my purpose here to go into the debate of whether pre- or post- version should be preferred. If we decide to change, this will be done in a separate PR.

Change inconsistent style of naming class members

---

src/details/ArborX_DetailsDistributor.hpp
src/details/ArborX_DetailsUtils.hpp
test/tstDetailsDistributedTreeImpl.cpp

Allow unmanaged views in sendAcrossNetwork

---

CMakeLists.txt

Propose alternate resolution for #433 
See #432

Specify minimum rocThrust version to resolve rocPRIM dependency issue

---

.mailmap

[skip ci] Add alias for WG

---

.jenkins
benchmarks/bvh_driver/bvh_driver.cpp
docker/Dockerfile.sycl
examples/callback/example_callback.cpp
examples/dbscan/ArborX_DetailsDBSCANVerification.hpp
src/details/ArborX_DetailsTreeConstruction.hpp

With the next Kokkos release most of the tests should work.

Add CI for SYCL

---

src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
src/details/ArborX_DetailsNode.hpp
src/details/ArborX_DetailsTreeConstruction.hpp
test/tstDetailsTreeConstruction.cpp

Introduce `BasicBoundingVolumeHierarchy` templated on `BoundingVolume` and let `BoundingVolumeHierarchy` be a type alias using `Box`.

Introduce BasicBoundingVolumeHierarchy<MemorySpace, BoundingVolume>

---

src/ArborX_BruteForce.hpp
src/details/ArborX_DetailsBruteForceImpl.hpp
test/CMakeLists.txt
test/Search_UnitTestHelpers.hpp
test/tstQueryTreeCallbacks.cpp
test/tstQueryTreeComparisonWithBoost.cpp
test/tstQueryTreeDegenerate.cpp

`BruteForce` tests all predicates against all primitives.  I have only implemented spatial queries at the moment.

Add BruteForce data structure

---

src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsDistributedTreeImpl.hpp
src/details/ArborX_DetailsHappyTreeFriends.hpp
src/details/ArborX_DetailsTreeTraversal.hpp
src/details/ArborX_DetailsTreeVisualization.hpp

Rational: Who needs so many friends anyway?
I need to grant access to private implementation of `BVH` some more places so instead of keep adding friends, I suggest we use the "Attorney-Client" idiom.

Use Attorney-Client idiom for BVH

---

src/ArborX_DBSCAN.hpp
src/details/ArborX_DetailsDBSCANCallback.hpp
src/details/ArborX_DetailsFDBSCAN.hpp

This is prerequisite to #508, just moving code around and renaming files.

Rename DBSCANCallback to FDBSCANCallback

---

src/details/ArborX_DetailsFDBSCANDenseBox.hpp

Missed one "boundary" spot when rebasing DenseBox branch on master

---

examples/dbscan/CMakeLists.txt
examples/dbscan/converter.cpp
examples/dbscan/dbscan.cpp

Motivation:
- it's a good idea
- comparison with PDSDBSAN can be done with a single set of files

Store dimension value in a datafile

---

README.md
examples/CMakeLists.txt
examples/simple_intersection/CMakeLists.txt
examples/simple_intersection/example_intersection.cpp

While helping people in the Argonne hackathon last week, I recognized that we don't have any simple examples to get people started. IMHO, a simple intersection serves as a good example so I more or less copied one of the manufactured solutions for querying the tree into an example that works without all the testing harness.

Add simple intersection example 

---

CMakeLists.txt

Update version string on the release branch

---

examples/CMakeLists.txt
examples/molecular_dynamics/CMakeLists.txt
examples/molecular_dynamics/example_molecular_dynamics.cpp

~Not asking for feedback, this is for collaborating with @streeve~

Add molecular dynamics example

---

examples/dbscan/dbscan.cpp

It was originally used to validate FOF halo finder, but that is no
longer necessary, and has not been used anywhere in months.

Remove unused printing out of cluster sizes and centers

---

test/CMakeLists.txt

Fixup `Kokkos_ENABLE_PTHREAD` is being deprecated

---

src/details/ArborX_DetailsHappyTreeFriends.hpp
src/details/ArborX_DetailsTreeNodeLabeling.hpp
test/CMakeLists.txt
test/tstDetailsTreeNodeLabeling.cpp

Introduce helper functions for label reduction on a hierarchy

---

.gitlab-ci.yml

This should fix that GitLab CI, see https://code.ornl.gov/ecpcitest/alexa/-/pipelines/181950.

use different master branch on GitLab CI

---

README.md

Fixes https://github.com/arborx/ArborX/pull/513#pullrequestreview-840513092.

Fix link to examples directory

---

src/details/ArborX_DetailsKokkosExtMinMaxOperations.hpp
src/details/ArborX_DetailsMutualReachabilityDistance.hpp
test/ArborXTest_StdVectorToKokkosView.hpp
test/CMakeLists.txt
test/tstDetailsMutualReachabilityDistance.cpp
test/tstDetailsTreeNodeLabeling.cpp

Add functionality to compute mutual reachability distances

---

examples/dbscan/ArborX_DBSCANVerification.hpp
test/tstQueryTreeIntersectsKDOP.cpp

I had to resolve some Kokkos header includes issue in another project and scanned ours just our curiosity.
Here are a couple trivial fixes.

Fix Kokkos header includes

---

src/details/ArborX_DetailsMortonCode.hpp
test/CMakeLists.txt
test/tstDetailsMortonCodes.cpp
test/tstDetailsTreeConstruction.cpp

Add 2D Morton codes

---

.gitlab-ci.yml

Update GitLab CI

---

examples/molecular_dynamics/example_molecular_dynamics.cpp
src/ArborX_BruteForce.hpp
src/ArborX_DBSCAN.hpp
src/ArborX_DistributedTree.hpp
src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsBatchedQueries.hpp
src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
src/details/ArborX_DetailsDistributedTreeImpl.hpp
src/details/ArborX_DetailsDistributor.hpp
src/details/ArborX_DetailsFDBSCANDenseBox.hpp
src/details/ArborX_DetailsSortUtils.hpp
src/details/ArborX_DetailsTreeConstruction.hpp
src/details/ArborX_DetailsTreeTraversal.hpp
src/details/ArborX_DetailsTreeVisualization.hpp
src/details/ArborX_DetailsUtils.hpp
src/details/ArborX_MinimumSpanningTree.hpp

Use specified execution space in view allocations

---

src/details/ArborX_Box.hpp
src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp
src/details/ArborX_KDOP.hpp

* Rename Kokkos::ArithmeticTraits::{max -> finite_max}
* Add Kokkos::ArithmeticTraits::finite_min
* Add int and long long specializations of finite_{min,max}
I would like to use these in #646

Update arithmetic traits

---

src/details/ArborX_Callbacks.hpp
test/tstDistributedTree.cpp
test/tstQueryTreeCallbacks.cpp

Remove last vestiges of InlineCallbackTag, and deprecate it

---

.gitlab-ci.yml

Try specifying custom CI build directory for gitlab

---

benchmarks/point_clouds/point_clouds.hpp

Nightly builds broke following the merge of kokkos/kokkos#4197

Fix nightly builds

---

src/details/ArborX_Ray.hpp
src/details/ArborX_Triangle.hpp
test/tstRay.cpp

The algorithm is described in Woop, S. et al. (2013), Watertight Ray/Triangle Intersection, Journal of Computer Graphics Techniques Vol. 2(1), https://jcgt.org/published/0002/01/05/

Implementation of the water tight ray-triangle intersection

---

src/details/ArborX_DetailsTreeTraversal.hpp
src/details/ArborX_Predicates.hpp

Drafted what we discussed in https://github.com/arborx/ArborX/pull/675#issuecomment-1191882034 so we can think where we want the customization point

Add `distance` member function to nearest predicate

---

src/geometry/ArborX_Box.hpp
src/geometry/ArborX_DetailsAlgorithms.hpp
src/geometry/ArborX_GeometryTraits.hpp
src/geometry/ArborX_Point.hpp
src/geometry/ArborX_Sphere.hpp
test/CMakeLists.txt
test/tstBoostGeometryAdapters.cpp
test/tstCompileOnlyGeometry.cpp
test/tstDetailsAlgorithms.cpp

Introduce GeometryTraits

---

src/details/ArborX_SpaceFillingCurves.hpp
src/geometry/ArborX_DetailsAlgorithms.hpp
test/tstDetailsAlgorithms.cpp

Get rid of centroid() in favor of returnCentroid()

---

src/geometry/ArborX_GeometryTraits.hpp
src/geometry/ArborX_HyperBox.hpp
src/geometry/ArborX_HyperPoint.hpp
src/geometry/ArborX_HyperSphere.hpp
test/tstDetailsAlgorithms.cpp

Depends on #714 for testing new geometries.

Introduce new multi-dimensional geometries

---

src/geometry/ArborX_DetailsAlgorithms.hpp

Don't know why I didn't notice it before. Makes no sense to duplicate those asserts.

Move static_assert in geometry algorithms to launchers

---

src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
src/details/ArborX_SpaceFillingCurves.hpp
src/geometry/ArborX_HyperBox.hpp
src/geometry/ArborX_HyperPoint.hpp
src/geometry/ArborX_HyperSphere.hpp
test/tstCompileOnlyTypeRequirements.cpp
test/tstDetailsAlgorithms.cpp
test/tstDetailsMortonCodes.cpp

Per https://github.com/arborx/ArborX/pull/717#discussion_r961611361

Delegate hyper-geometries to old ones for pre Kokkos-3.7

---

benchmarks/dbscan/ArborX_DBSCANVerification.hpp
src/ArborX_DBSCAN.hpp
src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsCartesianGrid.hpp
src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
src/details/ArborX_DetailsFDBSCANDenseBox.hpp
src/details/ArborX_DetailsMortonCode.hpp
src/details/ArborX_MinimumSpanningTree.hpp
src/geometry/ArborX_DetailsAlgorithms.hpp
src/geometry/ArborX_GeometryTraits.hpp

It makes code a bit easier to write, imho. But I don't know how others feel about it.

Introduce dimension_v

---

benchmarks/dbscan/print_timers.cpp

Fix compiler warning in print_timers

---

benchmarks/dbscan/data.hpp
benchmarks/dbscan/dbscan.cpp
benchmarks/dbscan/dbscan.hpp
benchmarks/dbscan/dbscan_timpl.hpp

This allows to generate arbitrary sized problems for DBSCAN.
I'm still not sure which parameters of the SS algorithm should be exposed to the user.
The algorithm is described in the paper: J. Gan and Y. Tao. "On the hardness and approximation of Euclidean DBSCAN." ACM Transactions on Database Systems (TODS), 2017.

Add Gan-Tao cluster generator

---

.gitlab-ci.yml

Fix gitlab

---

benchmarks/dbscan/dbscan_timpl.hpp
benchmarks/dbscan/print_timers.cpp
benchmarks/dbscan/print_timers.hpp
src/ArborX_DBSCAN.hpp
src/ArborX_HDBSCAN.hpp
src/details/ArborX_DetailsDendrogram.hpp
src/details/ArborX_MinimumSpanningTree.hpp

Per our discussion, demonstrating how we can achieve the custom timers with regular profiling regions.
I didn't put too much thinking on the actual labels that we use.
Haven't actually fully tested.

Prefer profiling regions to sections

---

src/details/ArborX_DetailsDistributedTreeImpl.hpp

It's been 2.5 years since the introduction (#356), so I consider it safe to remove them.

Remove deprecated queryDispatch calls in the distributed tree

---

src/details/ArborX_DetailsUnionFind.hpp
test/CMakeLists.txt
test/tstUnionFind.cpp

- Add union-find test
- Update `UnionFind` to have `memory_space` typedef and a `size()` function

Add testing for union-find

---

src/details/ArborX_DetailsSortUtils.hpp
src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp

Resurrecting and reorganizing #460.

Introduce KokkosExt::sortByKey

---

src/ArborX_DBSCAN.hpp
src/details/ArborX_DetailsFDBSCAN.hpp

Use half-traversal (#808) in the FDBSCAN algorithm.

Use half traversal in FDBSCAN

---

src/details/ArborX_DetailsCartesianGrid.hpp
src/details/ArborX_DetailsHalfTraversal.hpp
src/geometry/ArborX_GeometryTraits.hpp
test/boost_ext/KokkosPairComparison.hpp

Drive-by improvements spotted when looking into #819

Improve test helpers to print Kokkos pair

---

src/details/ArborX_DetailsDistributedTreeImpl.hpp

No new code, just moving it around within two functions (`forwardQueries`, `communicateResultsBack`), and putting it inside the blocks.
Also drive-by fixes for label names.

Reduce memory consumption when sending data in DistributedTree

---

benchmarks/CMakeLists.txt
benchmarks/develop/CMakeLists.txt
benchmarks/develop/develop.cpp

The goal is to have a placeholder for quick experimenting. Did not want to put into examples, as that may confuse users, or tests.

Add a develop benchmark

---

test/tstQueryTreeRay.cpp

Work around ROCm 5.2 ICE

---

benchmarks/dbscan/data.hpp
src/ArborX_DBSCAN.hpp

Workaround CUDA 11.0-11.3 issues

---

benchmarks/dbscan/dbscan.cpp
benchmarks/dbscan/dbscan.hpp
benchmarks/dbscan/dbscan_timpl.hpp
src/ArborX_HDBSCAN.hpp
src/details/ArborX_Dendrogram.hpp
src/details/ArborX_MinimumSpanningTree.hpp
test/tstDendrogram.cpp

Moved out of #825. 
I think it is not necessary to fully understand why it works for the review. Rather, I think we should just focus on the interface and make the code clean without exploring the algorithm in details.
The main thing I'm unsure about is the interface, and whether the hybrid mode should be a template argument in MST.

New dendrogram construction algorithm integrated with Boruvka

---

CMakeLists.txt
examples/CMakeLists.txt

Drive-by change: remove trailing whitespaces.

Update version to 1.5 dev

---

src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsDistributedTreeImpl.hpp
src/details/ArborX_DetailsHappyTreeFriends.hpp
src/details/ArborX_DetailsNode.hpp
src/details/ArborX_DetailsTreeConstruction.hpp
test/tstDetailsTreeConstruction.cpp

Separate leaf and internal nodes, use different node types

---

src/ArborX_LinearBVH.hpp
src/details/ArborX_DetailsBatchedQueries.hpp
src/details/ArborX_SpaceFillingCurves.hpp

Modernize space filling curve checks

---

src/details/ArborX_DetailsDistributedTreeImpl.hpp
src/details/ArborX_DetailsDistributedTreeNearest.hpp

Remove unused distances arg in Nearest dispatchQueryImpl

---

CHANGELOG.md

Missed how we usually did new features before build changes.

Minor reorder in CHANGELOG

---

CMakeLists.txt
examples/CMakeLists.txt

While I could have done 1.7, I think it's pretty safe to say that our next release is going to be 2.0.

Update version to 1.7 dev

---

test/tstDetailsKokkosExtUninitializedMemoryAlgorithms.cpp

It seems that the compiler (GCC-13) was optimizing out the write. Adding printing of the value variable at the end of the destructor also resulted in the correct behavior. Thus, I changed it to the volatile write.
Technically, using an object after its destruction is UB, so compiler is within its rights to ensure the simple write works as expected. 
Drive-by change: do synchronous deep_copy
This should fix our nightly tests.

Fix test for GCC-13

---

src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp
src/geometry/ArborX_DetailsAlgorithms.hpp

Make expanding things by radius a generic algorithm. Keep it in a distributed header for now.

Reorganize nearest to use approx_expand_by_radius

---

.github/workflows/windows.yml

Update Windows workflow

---

test/tstDistributedTree.cpp

Remove verbose nearest rays creation in the distributed test

---

test/CMakeLists.txt
test/tstDistributedTreeNearest.cpp
test/tstDistributedTreeSpatial.cpp

Split distributed test into spatial and nearest

---

.git-blame-ignore-revs
.jenkins/continuous.groovy
docker/Dockerfile.clang-format
scripts/check_format_cpp.sh
src/details/ArborX_Callbacks.hpp
src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp
src/geometry/ArborX_GeometryTraits.hpp
src/kokkos_ext/ArborX_DetailsKokkosExtUninitializedMemoryAlgorithms.hpp
test/tstCompileOnlyGeometry.cpp

Following kokkos and kokkos-kernels

Use clang-format-16

---

.jenkins/continuous.groovy
CMakeLists.txt
docker/Dockerfile
docker/Dockerfile.hipcc

- Require Kokkos 4.3
- Update CI using 4.2 to using 4.4

Require Kokkos 4.3

---

test/CMakeLists.txt
test/Search_UnitTestHelpers.hpp
test/tstKokkosToolsExecutionSpaceInstances.cpp

Opening to use as a base for discussion

Check that work is enqueued on the user-provided execution space instance

---

test/ArborX_EnableViewComparison.hpp

Remove Kokkos::Array's Proxy template arg in Boost specialization

---

src/ArborX_BruteForce.hpp
src/ArborX_DistributedTree.hpp
src/ArborX_LinearBVH.hpp

[Caught](https://github.com/arborx/ArborX/pull/1158#discussion_r1783333312) by @dalg24 in #1158.

Fix index CTAD

---

src/distributed/detail/ArborX_Distributor.hpp

Modify conditions on memory spaces in Distributor

---

examples/viz/tree_visualization.cpp
src/distributed/detail/ArborX_Distributor.hpp
src/interpolation/ArborX_InterpMovingLeastSquares.hpp
src/interpolation/detail/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp
src/interpolation/detail/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp
src/kokkos_ext/ArborX_KokkosExtMinMaxReduce.hpp
src/kokkos_ext/ArborX_KokkosExtSort.hpp
src/kokkos_ext/ArborX_KokkosExtStdAlgorithms.hpp
src/misc/ArborX_SortUtils.hpp
src/spatial/detail/ArborX_AccessTraits.hpp
test/ArborX_EnableViewComparison.hpp

Prefer View::rank() to View::rank

---

src/distributed/detail/ArborX_DistributedTreeNearest.hpp
src/distributed/detail/ArborX_DistributedTreeUtils.hpp
test/tstDistributedTreeNearest.cpp

It wasn't possible to run nearest queries with `double`:
```
<snip>/src/distributed/detail/ArborX_DistributedTreeNearestHelpers.hpp:94:12:
error: no viable constructor or deduction guide for deduction of template arguments of 'Sphere'
94 |     return Sphere{Details::convert<::ArborX::Point<DIM, Coordinate>>(point), r};
|            ^
<snip>/arborx/src/distributed/detail/ArborX_DistributedTreeNearestHelpers.hpp:144:60:
note: in instantiation of function template specialization
'ArborX::Details::Dispatch::approx_expand_by_radius<
ArborX::GeometryTraits::PointTag, ArborX::Point<3, double>>::apply<float>' requested here
144 |       typename GeometryTraits::tag_t<Geometry>, Geometry>::apply(geometry, r);
```
I realized we had a few instances of hardcoded `float` in the nearest queries. This PR …

Remove hardcoded float from DistributedTree nearest query

---

.jenkins/continuous.groovy

Getting CMake warnings otherwise.

Add -DCMAKE_CXX_EXTENSION=OFF back to GCC-13.3 build

---

examples/raytracing/example_raytracing.cpp
src/geometry/ArborX_Ray.hpp
test/tstDistributedTreeNearest.cpp
test/tstQueryTreeRay.cpp

Not sure yet whether it should be template on dimension.

Template Ray on precision

---

src/cluster/ArborX_DistributedDBSCAN.hpp
src/cluster/detail/ArborX_DistributedDBSCANHelpers.hpp

Works, but not very efficient right now. Have plans to reduce the cost of finding which points are core.

Add a general distributed DBSCAN implementation

---

src/geometry/algorithms/ArborX_Distance.hpp
test/tstDetailsAlgorithms.cpp

Fix wrong distance calculation for point-tetrahedron

---

src/geometry/algorithms/ArborX_Intersects.hpp
test/tstGeometryIntersects.cpp

Add segment-triangle intersection (3D only)

---

src/geometry/algorithms/ArborX_Intersects.hpp
test/tstGeometryIntersects.cpp

Fix 2D ellipsoid-segment intersection for degenerated segments

---

test/tstGeometryBarycentricCoordinates.cpp
test/tstGeometryCentroid.cpp
test/tstGeometryDistance.cpp
test/tstGeometryExpand.cpp
test/tstGeometryIntersects.cpp

Test geometry algorithms for both float and double

---

src/cluster/ArborX_DBSCAN.hpp

Simplify the noise marking code in DBSCAN.

Minor simplification in DBSCAN noise points labeling
